var wt_scrollposition = function (conf) {
    if(conf.mode == "page" && conf.type == "after" && conf.requestCounter == 1) {
        var scrollPositionConfig = {
            parameterConfiguration : {
                sendAsFigure : "",
                pageHeight : ""
            },
            roundResult : true
        };
        var pixel=conf.instance,event=pixel.wtTypeof(window.onbeforeunload)?"beforeunload":"unload",de=document.documentElement,scrollPosition=window.scrollY+window.innerHeight||self.scrollY+self.innerHeight||de&&de.scrollTop+de.clientHeight||document.body.scrollTop+document.body.clientHeight,YMax=window.innerHeight+window.scrollMaxY||self.innerHeight+self.scrollMaxY||de&&de.scrollHeight||document.body.offsetHeight,isScrollPositionSent=!1;
        pixel.registerEvent(window,"scroll",function(){var a=window.scrollY+window.innerHeight||self.scrollY+self.innerHeight||de&&de.scrollTop+de.clientHeight||document.body.scrollTop+document.body.clientHeight;a>scrollPosition&&(scrollPosition=a)});
        pixel.registerEvent(window,event,function(){if(!isScrollPositionSent&&(isScrollPositionSent=!0,scrollPosition=Math.round(100*(scrollPosition/YMax)),100<scrollPosition&&(scrollPosition=100),!isNaN(scrollPosition))){for(;;)if(scrollPositionConfig.roundResult&&0!=scrollPosition%5)scrollPosition++;else break;var a={};a["540"]=""+scrollPosition;scrollPositionConfig.parameterConfiguration.sendAsFigure&&(a[scrollPositionConfig.parameterConfiguration.sendAsFigure]=""+scrollPosition);scrollPositionConfig.parameterConfiguration.pageHeight&&
        (a[scrollPositionConfig.parameterConfiguration.pageHeight]=""+YMax);pixel.sendinfo({linkId:"wt_ignore",customClickParameter:a})}});
    }
};
(function(window, document) {
    var wt_marketingAutomationConfig = window.wt_marketingAutomationConfig || {
        trackId: "849715076759606",
        async: true,
        mediacode: "kid;wt_mc",
        keyword: "wt_kw",
        mcpBaseURL: "",
        widgetServiceUrl: ""
    };
    var WTCookie={getExpiryDate:function(b){var a=new Date,d=a.getTime();a.setTime(d+6E4*b);return a.toUTCString()},set:function(b,a,d){var g=document.location.hostname;-1==g.search(/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$/)&&(g=document.location.hostname.split("."),g=g[g.length-2]+"."+g[g.length-1]);b=3>=g.split(".")[0].length&&"undefined"!==typeof d&&d?b+"="+escape(a)+";path=/;expires="+WTCookie.getExpiryDate(d):3>=g.split(".")[0].length?b+"="+escape(a)+";path=/":"undefined"!==typeof d&&d?
            b+"="+escape(a)+";domain="+g+";path=/;expires="+WTCookie.getExpiryDate(d):b+"="+escape(a)+";path=/;domain="+g;document.cookie=b},get:function(b){for(var a=document.cookie.split(";"),d=0;d<a.length;d++){var g=a[d].substr(0,a[d].indexOf("=")),l=a[d].substr(a[d].indexOf("=")+1),g=g.replace(/^\s+|\s+$/g,"");if(g==b)return unescape(l)}return""}},MCPConfiguration=function(b){var a=b?b:null,d=null!==a&&"undefined"!==typeof a.globalVisitorIds?a.globalVisitorIds:!1,g=!1,l=[[/\.google\./,"q"],[/\.icq\./,"q"],
        [/suche\.t-online\./,"q"],[/search\.yahoo\./,"p"],[/search\.live\./,"q"],[/suche\.web\./,"su"],[/\.aolsvc\./,"query"],[/\.aol\./,"q"],[/suche\.freenet\./,"query"],[/\.preisroboter\./,"search"],[/suche\.gmx\./,"su"],[/search\.bearshare\./,"q"],[/\.lycos\./,"query"],[/\.ask\.com/,"q"],[/\.altavista\./,"q"],[/suche/,"q"],[/search/,"q"],[/suche/,"query"],[/search/,"query"],[/suche/,"su"],[/search/,"su"],[/suche/,"search"],[/search/,"search"],[/\.abacho\./,"q"],[/\.excite\./,"qkw"],[/\.billiger\./,"searchstring"],
        [/\.idealo\./,"s"],[/\.bing\./,"q"],[/\.wolframalpha\./,"i"],[/yandex\./,"text"],[/\.baidu\./,"wd"],[/ecosia\.org/,"q"],[/\.virgilio\.it/,"qs"],[/\.libero\.it/,"query"],[/\.seznam\.cz/,"q"],[/\.sogou\.com/,"query"],[/\.soso\.com/,"w"],[/\.so\.com/,"q"],[/\.yisou\.com/,"q"],[/\.youdao\.com/,"q"],[/\.panguso\.com/,"q"],[/\.jike\.com/,"q"],[/iask\.sina\.com\.cn/,"title"],[/\.zhongsou\.com/,"w"],[/search\.about\.com/,"q"],[/alice\.com/,"search"],[/cnn\.com\/search/,"query"],[/search\.daum\.net/,"q"],
        [/search\.yahoo\.com/,"p"],[/kvasir\.no/,"q"],[/mamma\.com/,"q"],[/arama\.mynet\.com/,"query"],[/search\.naver\.com/,"query"],[/onetonline\.org/,"s"],[/nova\.rambler\.ru/,"query"],[/search\.com/,"q"],[/finn\.no/,"finnkode"],[/search\.ke\.voila\.fr/,"rdata"],[/szukaj\.wp\.pl/,"q"],[/search\.yam\.com/,"k"],[/go\.mail\.ru/,"q"],[/m\.search\.rambler\.ru/,"query"],[/\.baidu\./,"word"],[/\.baidu\./,"oq"],[/\.baidu\./,"kw"],[/\.sogou\.com/,"keyword"],[/\.soso\.com/,"key"],[/\.soso\.com/,"query"],[/\.360\.cn/,
            "q"],[/sh\.qihoo\.com/,"q"],[/m\.sm\.cn/,"q"],[/www\.hao123\.com/,"word"],[/\.haosou\.com/,"q"],[/search\.tut\.by/,"query"],[/\.soseek\.org/,"search"],[/ixquick\.de/,"search"],[/ixquick\.com/,"search"],[/\.ecosia\.org/,"q"],[/\.mywebsearch\.com/,"searchfor"],[/megager\.de/,"eingabe"],[/suche\.aolsvc\.de/,"q"],[/\.sougou\.com/,"keyword"],[/duckduckgo\./,"q"],[/de\.wow\./,"q"],[/startpage\.com/,"query"],[/\.ecosia\.com/,"q"],[/schnell\-startseite\.de/,"q"],[/\.zapmeta\./,"q"],[/suche\.gmx\.net/,"q"],
        [/navigationshilfe\.t-online\.de/,"q"],[/\.fireball\.de/,"q"],[/\.izito\.de/,"q"],[/\.startxxl\.com/,"q"],[/www\.sm\.de/,"q"]],n=function(a,c){var b=t(a);return t(c?c:document.location.href)===b},m=function(a){try{return decodeURIComponent(a)}catch(c){return unescape(a)}},H=function(a){try{return encodeURIComponent(a)}catch(c){return escape(a)}},t=function(a){if("string"!==typeof a)return"";a=m(a).split("://");return"undefined"!==typeof a[1]&&(a=a[1].match(/^(?:[^\/]+:\/\/)?([^\/:]+)/g))&&"undefined"!==
    typeof a[0]?a[0].toLowerCase():""},r=function(a,c,b){if("string"!==typeof a)return b;var d=[];0<a.indexOf("?")&&(d=a.split("?")[1].replace(/&amp;/g,"&").split("#")[0].split("&"));for(a=0;a<d.length;a++)if(0===d[a].indexOf(c+"="))return m(d[a].substring(c.length+1).replace(/\+/g,"%20"));return b},s=function(){var a=WTCookie.get("wt_nv"),c=WTCookie.get("wt_nv_s");if(a&&"0"===a)return WTCookie.set("wt_nv","0",259200),!1;if(a&&"1"===a){if(!c)return WTCookie.set("wt_nv","0",259200),!1}else WTCookie.set("wt_nv",
        "1",259200),WTCookie.set("wt_nv_s","1");return!0},u=function(a,c,b){if(!a||null===a)return"";a=a.split(";");for(var d=0;d<a.length;d++){var e=r(b,a[d],!1);if(e)return c?a[d]+H("="+e):H(e)}return""},y=function(a,c){for(var b="",d=0;d<=c;d++)b+="0";b+=a;return b.substring(b.length-c,b.length)},B=function(b){if(null!==a&&"3"===a.cookie)return!1;var c;c=r(document.location.href,"wt_eid",!1);var h=r(document.location.href,"wt_t",!1),d=(new Date).getTime(),e=/^[0-9]{19}$/,h=h?parseInt(h)+9E5:d-9E5;c=c&&
    e.test(c)&&h>d?c:!1;if(c)return c;if(null!==a&&"1"===a.cookie&&a.eid)return a.eid;c=WTCookie.get("wt3_eid").split(";");b=b.split(",")[0];for(h=0;h<c.length;h++)if(-1!==c[h].indexOf(b+"|"))return c[h].replace(b+"|","").split("#")[0];window.wt_mcp_eid=window.wt_mcp_eid||b+"|"+("2"+y(Math.floor((new Date).getTime()/1E3),10)+y(Math.floor(1E6*Math.random()),8));return window.wt_mcp_eid.split("|")[1]};this.getExternalSearchPhrase=function(a,c){var b;a:{b=a?a:document.referrer;if(!n(b,c?c:document.location.href)){var d=
        t(b);if(d&&"string"===typeof d)for(var e=0,g=l.length;e<g;e++)if(-1!==d.search(l[e][0])){var m=r(b,l[e][1],!1);if(!1!==m){b=m?m:"not provided";break a}}}b=""}return b};this.getReferrerURL=function(a){a:{a=a?a:document.referrer;if(!n(a)&&(a=a.split(/^(http|https):\/\//g),"undefined"!==typeof a[2])){a=a[2].split("?")[0].split("#")[0];break a}a=""}return a};this.isNewVisitor=function(){return s()};this.getMediaCode=function(b,c){if(null!==a){var d=u(b,!0,c?c:document.location.href);if(a.config.campaignId||
        d)return a.config.campaignId?a.config.campaignId:d}return!1};this.getKeyword=function(b,c){if(null!==a){var d=u(b,!1,c?c:document.location.href);if(d)return d}return!1};this.getPixelConfiguration=function(){var b={};if(null!==a){a.config.contentId&&(b.contentId=a.config.contentId);a.config.linkId&&(b.linkId=a.config.linkId,b.customClickParameter=a.config.customClickParameter);a.config.customerId&&(b.cid=a.config.customerId);a.config.product&&(b.product=a.config.product);a.config.productStatus&&(b.productAction=
        "conf"==a.config.productStatus?"buy":a.config.productStatus);a.config.productCost&&(b.productPrice=a.config.productCost);a.config.productQuantity&&(b.productQuantity=a.config.productQuantity);a.config.orderValue&&(b.orderValue=a.config.orderValue);a.config.orderId&&(b.orderId=a.config.orderId);a.config.currency&&(b.currency=a.config.currency);a.config.internalSearch&&(b.searchPhraseInternal=a.config.internalSearch);a.config.customEcommerceParameter&&"undefined"!==typeof a.config.customEcommerceParameter[760]&&
    (b.productSoldOut="1"===a.config.customEcommerceParameter[760]);if(a.config.couponValue||a.config.customEcommerceParameter&&"undefined"!==typeof a.config.customEcommerceParameter[563])b.couponValue=a.config.couponValue||a.config.customEcommerceParameter[563]||"";a.config.customParameter&&(b.customParameter=a.config.customParameter);a.config.customCampaignParameter&&(b.customCampaignParameter=a.config.customCampaignParameter);a.config.customEcommerceParameter&&(b.customEcommerceParameter=a.config.customEcommerceParameter);
        a.config.customSessionParameter&&(b.customSessionParameter=a.config.customSessionParameter);a.config.contentGroup&&(b.contentGroup=a.config.contentGroup);a.config.productCategory&&(b.productCategory=a.config.productCategory);a.config.urmCategory&&(b.urmCategory=a.config.urmCategory);a.config.crmCategory&&(b.crmCategory=a.config.crmCategory)}return b};this.getEID=function(a){return B(a)};this.getGEID=function(){var b;null!==a&&a.geid?b=a.geid:(b=WTCookie.get("wt_geid")?WTCookie.get("wt_geid"):!1,"68934a3e9455fa72420237eb"===
    b?b=!1:!b&&d&&(g=!0));return b};this.getFEID=function(){var b;null!==a&&a.feid?b=a.feid:(b=WTCookie.get("wt_feid")?WTCookie.get("wt_feid"):!1)&&-1===b.search(/^[0-9a-f]{32}$/)?b=!1:!b&&d&&(g=!0);return b};this.waitOfGlobalVisitorIds=function(){return g}};window.wt_isGlobalVisitorIdTriggerStarted=!1;
    var _include=function(b){b="https:"===document.location.protocol?"https://"+b:"http://"+b;if(wt_marketingAutomationConfig.async||"complete"===document.readyState||"interactive"===document.readyState){var a=document.createElement("script");a.type="text/javascript";a.async=!0;a.defer=!0;a.src=b;(document.getElementsByTagName("head")[0]||document.body).appendChild(a)}else b='<script type="text/javascript" '+('src="'+b+'">'),b+="\x3c/script>",document.write(b)},_startGlobalVisitorIdTrigger=function(b){var a=
        2E3,d=window.setInterval(function(){if("function"===typeof wt_geid||0>=a)if(window.clearInterval(d),"function"===typeof wt_geid)var g=2E3,l=window.setInterval(function(){if(WTCookie.get("wt_geid")||0>=g)window.clearInterval(l),_pushMCPConfiguration("async-data",b);g-=100},100);else _pushMCPConfiguration("async-data",b);a-=100},100)},_getMCPInputKeys=function(b){var a=new MCPConfiguration(b),d=a.getPixelConfiguration();d.newVisitor=a.isNewVisitor();var g=a.getEID(wt_marketingAutomationConfig.trackId);
        g&&(d.eid=g);if(g=a.getGEID())d.geid=g;var l=a.getFEID();l&&(d.feid=l);g&&l||(!a.waitOfGlobalVisitorIds()||window.wt_isGlobalVisitorIdTriggerStarted)||(d.waitForAsyncData=!0,window.wt_isGlobalVisitorIdTriggerStarted=!0,_startGlobalVisitorIdTrigger(b));if(b=a.getMediaCode(wt_marketingAutomationConfig.mediacode))d.mediacode=b;if(b=a.getKeyword(wt_marketingAutomationConfig.keyword))d.keyword=b;if(b=a.getReferrerURL())d.referrer=b;if(a=a.getExternalSearchPhrase())d.searchPhraseExternal=a;return d},_getMCPConfiguration=
        function(b){var a={};b&&("object"===typeof b.tt&&(a.teaserAttribute=b.tt.teaserAttribute),a.trackingPixel=b);a.trackId=wt_marketingAutomationConfig.trackId.split(",");a.segments={};a.url=document.location.href;a.inputKeys=_getMCPInputKeys(b);a.waitForAsyncData="undefined"!==typeof a.inputKeys.waitForAsyncData?a.inputKeys.waitForAsyncData:!1;wt_marketingAutomationConfig.widgetServiceUrl&&(a.widgetServiceUrl=wt_marketingAutomationConfig.widgetServiceUrl);return a},_pushMCPConfiguration=function(b,a){"head"===
    b&&(window.wt_mcp_config=window.wt_mcp_config||[]);wt_mcp_config.push([b,_getMCPConfiguration(a)])};
    (function(b){b.wt_teaserTracking=function(a){var d=b.wt_teaserTrackingConfig||{clearConversions:"1",engagements:"auto",teaserAttribute:"data-wt-teaser"},g=function(a){(function(a){"page"!==a.mode&&"config"!==a.mode||"before"!==a.type||1!==a.requestCounter||function(b,l,g){var r={},s="undefined"!==typeof wt_ttMaxTeaser?wt_ttMaxTeaser:50,u="undefined"!==typeof wt_ttMaxLength?wt_ttMaxLength:10,y="undefined"!==typeof wt_ttMaxNameLength?wt_ttMaxNameLength:110,B="undefined"!==typeof wt_teaserEngagements?
        wt_teaserEngagements:!1,ca="undefined"!==typeof wt_teaserConversions?wt_teaserConversions:!1,c={_520:"520",_521:"521",_522:"522",_523:"523",_524:"524",_525:"525",_526:"526",_527:"527",_528:"528",_529:"529",_530:"530",_531:"531",_532:"532",_533:"533"},h={};h[c._520]=[];h[c._521]=[];h[c._522]=[];h[c._523]=[];h[c._524]=[];h[c._525]=[];h[c._526]=[];h[c._527]=[];h[c._528]=[];h[c._529]=[];h[c._530]=[];h[c._531]=[];h[c._532]=[];h[c._533]=[];var x=0,e=l.wt_tt=b,da=-1!==l.document.location.href.indexOf("wt_debug=1")?
        !0:-1!==g.cookie.indexOf("wt_debug=1"),I=!1,J=!1,z=function(a,b,e,d,f,l,g,n,p,q,k,m,r,s,t){h[c._520].push(a);h[c._521].push(b);h[c._522].push(e);h[c._523].push(d);h[c._524].push(f);h[c._525].push(l);h[c._526].push(g);h[c._527].push(n);h[c._528].push(p);h[c._529].push("undefined"!==k?k:"");h[c._530].push("undefined"!==m?m:"");h[c._531].push("undefined"!==r?r:"");h[c._532].push("undefined"!==s?s:"");h[c._533].push("undefined"!==t?t:"");q&&"1"==d&&(d={ck:{}},d.ck[c._520]=a,d.ck[c._521]=b,d.ck[c._522]=
            e,d.ck[c._526]=g,d.ck[c._527]=n,d.ck[c._529]="undefined"!==k?k:"",d.ck[c._530]="undefined"!==m?m:"",d.ck[c._531]="undefined"!==r?r:"",d.ck[c._532]="undefined"!==s?s:"",d.ck[c._533]="undefined"!==t?t:"",d.vic="1",K(v(d)),L(d))},ea=function(a){h[c._520].splice(0,a);h[c._521].splice(0,a);h[c._522].splice(0,a);h[c._523].splice(0,a);h[c._524].splice(0,a);h[c._525].splice(0,a);h[c._526].splice(0,a);h[c._527].splice(0,a);h[c._528].splice(0,a);h[c._528].splice(0,a);h[c._529].splice(0,a);h[c._530].splice(0,
        a);h[c._531].splice(0,a);h[c._532].splice(0,a);h[c._533].splice(0,a)},p=function(){if(da&&"undefined"!==typeof console&&"undefined"!==typeof console.log){for(var a=0;a<arguments.length;a++)"string"===typeof arguments[a]&&(arguments[a]="TeaserTracking->"+arguments[a]);console.log.apply(this,arguments)}},A=function(){var a=g.documentElement,a=l.scrollY+l.innerHeight||a&&a.scrollTop+a.clientHeight||g.body.scrollTop+g.body.clientHeight;a>x&&(p("new scroll position",a),x=a);for(var b in r)if(a=r[b+""],
        ""==a.hidden&&!a.seen&&a.height<=x){var e;a:{if(e=a)for(var h=g.querySelectorAll("*["+d.teaserAttribute+"]"),C=0;C<h.length;C++)if(h[C]===e.tag){e=!0;break a}e=!1}e&&0<s&&(p("new teaser view",a),z(f(a.json,c._520),f(a.json,c._521),f(a.json,c._522),"1","","",f(a.json,c._526),f(a.json,c._527),"",a.viewIsClick,f(a.json,c._529),f(a.json,c._530),f(a.json,c._531),f(a.json,c._532),f(a.json,c._533)),s--,a.seen=!0)}},K=function(a){e.getCookie("wt_tc")&&e.setCookie("wt_tc","",-3600);e.setCookie("wt_tc",a)},
        L=function(a){var b=D(e.getCookie("wt_tcc"))||[],d;a:{for(d=0;d<b.length;d++)if(f({ck:b[d]},"1")==f(a,c._521)){p("contains teaser in cookie",b[d],a);d=!0;break a}d=!1}for(d||b.push([f(a,c._520),f(a,c._521),f(a,c._522),f(a,c._526),f(a,c._527),"undefined"!==typeof a.vic||"undefined"!==typeof a.ctc?"1":"0",f(a,c._529),f(a,c._530),f(a,c._531),f(a,c._532),f(a,c._533)]);4E3<escape(v(b)).length;)b.shift();e.setCookie("wt_tcc",v(b))},M=function(a,b){if((a.which&&1==a.which||a.button&&1==a.button)&&b){if(b.wtTeaser){p("click teaser",
            b.wtTeaser);var d;d="&ct=wt_ignore"+("&ck"+c._520+"="+e.wtEscape(f(b.wtTeaser.json,c._520)));d+="&ck"+c._521+"="+e.wtEscape(f(b.wtTeaser.json,c._521));d+="&ck"+c._522+"="+e.wtEscape(f(b.wtTeaser.json,c._522));d+="&ck"+c._523+"=";d+="&ck"+c._524+"=1";d+="&ck"+c._525+"=";d+="&ck"+c._526+"="+e.wtEscape(f(b.wtTeaser.json,c._526));d+="&ck"+c._527+"="+e.wtEscape(f(b.wtTeaser.json,c._527));d+="&ck"+c._528+"=";d+="&ck"+c._529+"="+e.wtEscape(f(b.wtTeaser.json,c._529));d+="&ck"+c._530+"="+e.wtEscape(f(b.wtTeaser.json,
            c._530));d+="&ck"+c._531+"="+e.wtEscape(f(b.wtTeaser.json,c._531));d+="&ck"+c._532+"="+e.wtEscape(f(b.wtTeaser.json,c._532));d+="&ck"+c._533+"="+e.wtEscape(f(b.wtTeaser.json,c._533));e.quicksend(e.wtEscape(e.contentId.split(";")[0])+",1,"+e.baseparams(),d)}K(v(b.wtTeaser.json));L(b.wtTeaser.json)}},N=function(a,c){if(a&&c){if("area"==a.tagName.toLowerCase()||"a"==a.tagName.toLowerCase())a.wtTeaser=c,p("register new teaser link - click",c),e.registerEvent(a,"click",function(b){M(b,a)});for(var b="undefined"!==
        typeof a.children&&"number"===typeof a.children.length?a.children:a.childNodes,d=0;d<b.length;d++)1===b[d].nodeType&&("area"==b[d].tagName.toLowerCase()||"a"==b[d].tagName.toLowerCase()?(b[d].wtTeaser=c,p("register new teaser link - click",c),function(a){e.registerEvent(b[a],"click",function(c){M(c,b[a])})}(d)):N(b[d],c))}},fa=function(a){var b={top:0,height:0};if(!a)return b;if("undefined"!=typeof a.offsetTop)for(b.height=a.offsetHeight;a&&"BODY"!=a.tagName;)b.top+=parseInt(a.offsetTop),a=a.offsetParent;
            return b.top+b.height},O=function(a){if(a&&null!==a){if("undefined"!==typeof a.style&&null!==a.style&&"none"==a.style.display)return!0;a="undefined"!==typeof a.children&&"number"===typeof a.children.length?a.children:a.childNodes;for(var b=0;b<a.length;b++)if(1===a[b].nodeType&&("undefined"!==typeof a[b].style&&null!==a[b].style&&"none"==a[b].style.display||O(a[b])))return!0}return!1},P=function(){var a,b,d=0,f,g="&ct=wt_ignore",n;for(n in c){var k=n+"";b=h[c[k]];f=b.length<=u?b.length:u;a=[];for(var m=
            0;m<f;m++)d++,a.push(b[m]);g+="&ck"+c[k]+"="+e.wtEscape(a.join(";"))}0<d&&(e.quicksend(e.wtEscape(e.contentId.split(";")[0])+",1,"+e.baseparams(),g),p("send teaser action",g),ea(f));l.setTimeout(function(){P()},1E3)},Q=function(a,b){a.length>b&&(a=a.substring(0,b-3)+"...");return a},f=function(a,b){return"undefined"!==typeof a.ck[b]?Q(a.ck[b],y):""},v=function(a){var b,c,e,d="";switch(typeof a){case "object":if(a){if(a.constructor==Array){for(c=0;c<a.length;++c)b=v(a[c]),d&&(d+=","),d+=b;return"["+
            d+"]"}if("undefined"!=typeof a.toString){for(e in a)c=e+"",b=v(a[c]),"function"!=typeof b&&(d&&(d+=","),d+=v(c)+":"+b);return"{"+d+"}"}}return"null";case "string":e=a.length;d='"';for(c=0;c<e;c+=1)if(b=a.charAt(c)," "<=b){if("\\"==b||'"'==b)d+="\\";d+=b}else switch(b){case "\b":d+="\\b";break;case "\f":d+="\\f";break;case "\n":d+="\\n";break;case "\r":d+="\\r";break;case "\t":d+="\\t";break;default:b=b.charCodeAt(0),d+="\\u00"+Math.floor(b/16).toString(16)+(b%16).toString(16)}return d+'"';case "number":return isFinite(a)?
            String(a):"null";case "boolean":return String(a);default:return"null"}},w=function(a){if(a&&"{"==a.charAt(0)&&"}"==a.charAt(a.length-1))try{var b=eval("("+a+")");if(b&&null!==b)return b}catch(c){}return!1},D=function(a){if(a&&"["==a.charAt(0)&&"]"==a.charAt(a.length-1))try{var b=eval("("+a+")");if(b&&null!==b)return b}catch(c){}return!1},E=function(a){return a?"object"!==typeof a.ck||"string"!==typeof a.ck[c._520]&&"string"!==typeof a.ck[c._521]?!1:!0:!1};b=function(a,b){for(var c=0;c<b.length;c++)if(Q(b[c],
        y)===a)return c;return!1};l.wt_tt.tt=l.wt_tt.tt||{version:"4.1.9",teaserParameterIds:c,checkTeaserCookie:function(){if(e.getCookie("wt_tc")&&("manual"!=d.engagements||B)&&E(w(e.getCookie("wt_tc")))){var a=w(e.getCookie("wt_tc"));p("find teaser engagement",a);z(f(a,c._520),f(a,c._521),f(a,c._522),"","","1",f(a,c._526),f(a,c._527),"",!1,f(a,c._529),f(a,c._530),f(a,c._531),f(a,c._532),f(a,c._533))}},checkTeaserConversions:function(){(e.config.orderValue||"1"===ca)&&e.getCookie("wt_tc")&&"1"===d.clearConversions&&
        (p("clear teaser conversions"),e.setCookie("wt_tc","",-3600))},searchTeaser:function(){for(var a=g.querySelectorAll("*["+d.teaserAttribute+"]"),b=0,h=a.length;b<h;b++)if("object"!==typeof a[b].wtTeaser)for(var l=a[b].attributes,n=0;n<l.length;n++)if(l[n].name===d.teaserAttribute&&E(w(l[n].value))){var k=w(l[n].value),m={json:k,tag:a[b],height:fa(a[b]),hidden:O(a[b]),seen:"undefined"!==typeof k.ckv,viewIsClick:"undefined"!==typeof k.vic,connectConversion:"undefined"!==typeof k.ctc};N(m.tag,m);r[f(k,
            c._521)?f(k,c._521):f(k,c._520)]=m;a[b].wtTeaser=m;m.hidden&&function(a){e.registerEvent(a,"mouseover",function(b){a&&"object"==typeof a.wtTeaser&&!a.wtTeaser.seen&&(b=a.wtTeaser.json,a.wtTeaser.hidden=!1,a.wtTeaser.seen=!0,z(f(b,c._520),f(b,c._521),f(b,c._522),"1","","",f(b,c._526),f(b,c._527),"",!1,f(b,c._529),f(b,c._530),f(b,c._531),f(b,c._532),f(b,c._533)))})}(m.tag)}p("search teaser",r)},startScrollPosition:function(){I?(p("scroll position is already started"),A()):(I=!0,x=l.innerHeight||self.innerHeight||
            g.documentElement&&g.documentElement.clientHeight||g.body.clientHeight,p("start scroll position",x),A(),e.registerEvent(l,"scroll",A))},sendTeaserAction:function(){J?p("send teaser actions is already started"):(J=!0,P())},addClickParameter:z,teaserAttribute:d.teaserAttribute,setScrollPos:A};if("page"===a.mode&&(e.orderValue||"conf"===e.productStatus||"undefined"!==typeof wt_teaserConversions&&"1"===wt_teaserConversions))if(e.config.customSid||(e.config.customSid=""),!e.product&&e.getCookie("wt_tc")&&
    E(w(e.getCookie("wt_tc"))))b=w(e.getCookie("wt_tc")),e.config.customSid+="&ck"+c._520+"="+e.wtEscape(f(b,c._520)),e.config.customSid+="&ck"+c._521+"="+e.wtEscape(f(b,c._521)),e.config.customSid+="&ck"+c._522+"="+e.wtEscape(f(b,c._522)),e.config.customSid+="&ck"+c._523+"=",e.config.customSid+="&ck"+c._524+"=",e.config.customSid+="&ck"+c._525+"=",e.config.customSid+="&ck"+c._526+"="+e.wtEscape(f(b,c._526)),e.config.customSid+="&ck"+c._527+"="+e.wtEscape(f(b,c._527)),e.config.customSid+="&ck"+c._528+
        "=1",e.config.customSid+="&ck"+c._529+"="+e.wtEscape(f(b,c._529)),e.config.customSid+="&ck"+c._530+"="+e.wtEscape(f(b,c._530)),e.config.customSid+="&ck"+c._531+"="+e.wtEscape(f(b,c._531)),e.config.customSid+="&ck"+c._532+"="+e.wtEscape(f(b,c._532)),e.config.customSid+="&ck"+c._533+"="+e.wtEscape(f(b,c._533)),p("find teaser conversion",e.config.customSid);else if(e.product&&e.getCookie("wt_tcc")&&D(e.getCookie("wt_tcc"))){for(var k=D(e.getCookie("wt_tcc")),ga=e.product.split(";"),R=e.productCost?e.productCost.split(";"):
        [],S=[],T=[],U=[],V=[],W=[],F=[],X=[],Y=[],Z=[],$=[],aa=[],q=0;q<k.length;q++){var G=b(k[q][1],ga),ba="undefined"!==typeof k[q][5]&&"1"===k[q][5];if(!1!==G||ba)S.push(k[q][0]),T.push(k[q][1]),U.push(k[q][2]),V.push(k[q][3]),W.push(k[q][4]),X.push(k[q][6]),Y.push(k[q][7]),Z.push(k[q][8]),$.push(k[q][9]),aa.push(k[q][10]),ba?F.push("1"):F.push("undefined"!==typeof R[G]?R[G]:"1")}e.config.customSid+="&ck"+c._520+"="+e.wtEscape(S.join(";"));e.config.customSid+="&ck"+c._521+"="+e.wtEscape(T.join(";"));
        e.config.customSid+="&ck"+c._522+"="+e.wtEscape(U.join(";"));e.config.customSid+="&ck"+c._523+"=";e.config.customSid+="&ck"+c._524+"=";e.config.customSid+="&ck"+c._525+"=";e.config.customSid+="&ck"+c._526+"="+e.wtEscape(V.join(";"));e.config.customSid+="&ck"+c._527+"="+e.wtEscape(W.join(";"));e.config.customSid+="&ck"+c._528+"="+e.wtEscape(F.join(";"));e.config.customSid+="&ck"+c._529+"="+e.wtEscape(X.join(";"));e.config.customSid+="&ck"+c._530+"="+e.wtEscape(Y.join(";"));e.config.customSid+="&ck"+
            c._531+"="+e.wtEscape(Z.join(";"));e.config.customSid+="&ck"+c._532+"="+e.wtEscape($.join(";"));e.config.customSid+="&ck"+c._533+"="+e.wtEscape(aa.join(";"));p("find teaser conversion",e.config.customSid);e.setCookie("wt_tcc","",-3600)}}(a.instance,b,document)})(a)};document.querySelectorAll&&document.querySelector||function(){var a=document.styleSheets&&document.styleSheets[0]||document.createStyleSheet&&document.createStyleSheet(),b=function(b,d){var g=document.all,n=[];a.addRule(b,"foo:bar");for(var s=
        0,u=g.length;s<u&&("bar"!==g[s].currentStyle.foo||(n.push(g[s]),d));s++);a.removeRule(0);return n};document.querySelectorAll=function(a){try{return b(a,!0)}catch(d){}return[]};document.querySelector=function(a){try{return b(a,!1)[0]||null}catch(d){}return null}}();(function(a,b){if("undefined"===typeof b.pluginIncludeTeaserTracking||"undefined"!==typeof b.pluginIncludeTeaserTracking&&("object"!==typeof b.tt||"object"===typeof b.tt&&!b.tt.teaserAttribute))b.pluginIncludeTeaserTracking=!0,g(a);1===
    a.requestCounter&&("page"===a.mode&&"after"===a.type&&(wt_tt.tt.checkTeaserCookie(),wt_tt.tt.checkTeaserConversions(),wt_tt.tt.searchTeaser(),wt_tt.tt.startScrollPosition(),wt_tt.tt.sendTeaserAction()),"config"===a.mode&&"before"===a.type&&(wt_tt.tt.searchTeaser(),wt_tt.tt.startScrollPosition(),wt_tt.tt.sendTeaserAction()))})(a,a.instance)};b.wts=b.wts||[];b.wts.push(["wt_teaserTracking"])})(window);
    (function(b){b.wt_testingOptimization=function(a){if("page"===a.mode&&"after"===a.type&&1===a.requestCounter){var d=a.instance;b.setTimeout(function(){d.testingInterval=b.setInterval(function(){if("string"===typeof wt_tox_ab&&""!==wt_tox_ab){var a=b.wt_tox_ab;b.wt_tox_ab="";d.sendinfo({linkId:"webtrekk_ignore",customSid:"&tox="+d.wtEscape(d.wtUnescape(a))})}},25)},1E3)}};b.wts=b.wts||[];b.wts.push(["wt_testingOptimization"])})(window);
    (function(b){b.wt_marketingAutomation=function(a){if("after"===a.type&&("page"===a.mode||"config"===a.mode)||"before"===a.type&&("link"===a.mode||"click"===a.mode)){var b=a.instance,g="update";"page"===a.mode&&1===a.requestCounter?g="body":"config"===a.mode&&(g="config");_pushMCPConfiguration(g,b)}};b.wts=b.wts||[];b.wts.push(["wt_marketingAutomation"])})(window);
    (function(b){var a=[];b.wt_dfp=b.wt_dfp||[];b.wt_mcp_config=b.wt_mcp_config||[];var d=function(d){var g="string"===typeof d[0]&&d[0]?d[0]:!1;d="function"===typeof d[1]&&d[1]?d[1]:!1;g&&d&&(b.wt_dfp.fallback?d("",[]):(a.push(d),"init"===g?b.wt_mcp_config.push(["dmp-init",_getMCPConfiguration(),d]):"display"===g&&b.wt_mcp_config.push(["dmp-display",d])))},g=function(){b.setTimeout(function(){if("object"===typeof b.wt_mcp_config&&b.wt_mcp_config instanceof Array){b.wt_dfp.fallback=!0;for(var d=0,g=a.length;d<
    g;d++)a[d]("",[])}},2E3)};(function(){for(var a=0;a<b.wt_dfp.length;a++)d(b.wt_dfp[a]);b.wt_dfp={push:d,length:0,fallback:!1};g()})()})(window);var _init=function(){var b=wt_marketingAutomationConfig.mcpBaseURL;b||(b="cdn.mateti.net/mcp/onsite.min.js");_include(b);_pushMCPConfiguration("head")};_init();
})(window, document);

var webtrekkConfig = window.webtrekkConfig || {
    trackId : "849715076759606"
    , trackDomain : "tp.deutsche-bank.de"
    , domain : "www.deutsche-bank.de"
    , cookie : "1"
    , contentId : ""
    , form:"1"
    , formAttribute:"data-wtname"
    , formAnonymous:"1"
    , tabBrowsing:false
    , execRTA:false
    , execCDB:false
    , executePluginFunction:"wt_teaserTracking;wt_marketingAutomation;wt_scrollposition"
    , fileSuffix : true
};

/**
 ************ Don't change anything beyond this line ************
 ********************* Start webtrekk_v441.js *********************
 */
(function(k){k.webtrekkUnloadObjects=k.webtrekkUnloadObjects||[];k.webtrekkLinktrackObjects=k.webtrekkLinktrackObjects||[];k.webtrekkHeatmapObjects=k.webtrekkHeatmapObjects||[];var D=function(a){a.getJSON=function(a){if("string"===typeof a&&a&&"{"===a.charAt(0)&&"}"===a.charAt(a.length-1))try{var c=(new Function("return "+a))();if("object"===typeof c)return c}catch(b){}return null};a.parseJSON=function(d,c){for(var b in d){var f=b;if("object"===typeof d[f])"undefined"!==typeof a.jsonPara[f]&&"object"!==
    typeof a.config[a.jsonPara[f][0]]&&(a.config[a.jsonPara[f][0]]={}),a.parseJSON(d[f],f);else if(c){if(isNaN(parseInt(f))||500>parseInt(f))a.config[a.jsonPara[c][0]][f]=d[f]}else"undefined"!==typeof a.jsonPara[f]&&(a.config[a.jsonPara[f][0]]=d[f])}};a.getMappingParam=function(d){var c=d.split(""),b,f,h;for(b=0;b<c.length;b++)if(!isNaN(parseInt(c[b]))){f=b;break}f?(c=d.substr(0,f),h=d.substr(f,d.length-1)):c=d;return{mapping:"undefined"!==typeof a.jsonPara[c]?a.jsonPara[c][0]:!1,index:h?h:!1}}},E=function(a){a.checkAsynchron=
        function(a,c,b,f){if("undefined"!==typeof k[a])return c?c(!0,b):1;if(0>=f)return c?c(!1,b):1;k.setTimeout(function(){b.checkAsynchron(a,c,b,f-100)},100);return 1};a.loadAsynchron=function(d,c,b,f){a.include(d)&&a.checkAsynchron(c,b?b:!1,a,f?f:2E3)};a.include=function(a){if(!document.createElement)return!1;var c=document.getElementsByTagName("head").item(0),b=document.createElement("script");b.setAttribute("language","javascript");b.setAttribute("type","text/javascript");b.setAttribute("src",a);c.appendChild(b);
        return!0}},F=function(a){a.registerEvent=function(d,c,b){d.addEventListener?("webkitvisibilitychange"===c&&a.unregisterEvent(d,c,b),d.addEventListener(c,b,!1)):d.attachEvent&&("beforeunload"!==c&&"webkitvisibilitychange"!==c||a.unregisterEvent(d,c,b),d.attachEvent("on"+c,b))};a.unregisterEvent=function(a,c,b){a.removeEventListener?a.removeEventListener(c,b,!1):a.detachEvent&&a.detachEvent("on"+c,b)}},G=function(a){a.getTimezone=function(){return Math.round(-1*((new Date).getTimezoneOffset()/60))};
        a.maxlen=function(a,c){return a&&a.length>c?a.substring(0,c-1):a};a.indexOf=function(a,c,b){return a.indexOf(c,b?b:0)};a.wtTypeof=function(a){return"undefined"!==typeof a?1:0};a.wtLength=function(a){return"undefined"!==typeof a?a.length:0};a.wtEscape=function(a){try{return encodeURIComponent(a)}catch(c){return escape(a)}};a.wtUnescape=function(a){try{return decodeURIComponent(a)}catch(c){return unescape(a)}};a.getAttribute=function(a,c){return"string"===typeof a.getAttribute(c)?a.getAttribute(c):
        "object"===typeof a.getAttribute(c)&&"object"===typeof a.attributes[c]&&null!==a.attributes[c]?a.attributes[c].nodeValue:""};a.plugInArray=function(a,c){if("object"!==typeof a)return!1;for(var b=0;b<a.length;b++){var f=RegExp(a[b].toLowerCase(),"g");if(-1!==c.toLowerCase().search(f))return a[b]}return!1}},H=function(a){a.decrypt=function(d){var c="";if(d)try{c=a.wtUnescape(d.replace(/([0-9a-fA-F][0-9a-fA-F])/g,"%$1"))}catch(b){}return c};a.checkSC=function(d){if("string"!==typeof a.secureConfig)return!1;
        for(var c=a.secureConfig.split(";"),b=0;b<c.length;b++)if(c[b]===d)return!0;return!1}},I=function(a){a.wtHref=function(){return a.wtLocation().href};a.wtLocation=function(){return document.location};a.urlParam=function(d,c,b){if(!d||null===d||"undefined"===typeof d)return b;var f=[];0<d.indexOf("?")&&(f=d.split("?")[1].replace(/&amp;/g,"&").split("#")[0].split("&"));for(d=0;d<f.length;d++)if(0===f[d].indexOf(c+"="))return a.wtUnescape(f[d].substring(c.length+1).replace(/\+/g,"%20"));return b};a.isOwnDomain=
        function(d){var c="";if(a.domain)if(0===a.domain.toUpperCase().indexOf("REGEXP:")){if(c=RegExp(a.domain.substring(7),"i"),c.test(a.getDomain(d)))return!0}else{c=a.domain.split(";");d=a.getDomain(d);for(var b=0;b<c.length;b++)if(d===c[b])return!0}return!1};a.getDomain=function(d){if("string"!==typeof d)return"";d=a.wtUnescape(d);d=d.split("://")[1];var c=RegExp("^(?:[^/]+://)?([^/:]+)","g");return"undefined"!==typeof d&&(d=d.match(c),d[0])?d[0].toLowerCase():""}},x=function(a,d,c){var b=RegExp(d+"="+
    c);c=document.location.href;d=(new Date).getTime();b=b.exec(c);c=/wt_t=([\d]{13})/.exec(c);return b&&("undefined"!==typeof b[1]&&c&&"undefined"!==typeof c[1])&&parseInt(c[1])+9E5>d?a.wtUnescape(b[1]):!1},J=function(a){var d=!1;a.baseparams=function(){var c=screen.width+"x"+screen.height+",",c=c+(("undefined"!==typeof screen.colorDepth?screen.colorDepth:screen.pixelDepth)+","),b;b=navigator.cookieEnabled;b="boolean"!==typeof b?-1!==document.cookie.indexOf("="):b;c=c+(b?"1,":"0,")+((new Date).getTime()+
    ",");if(a.referrerOncePerSession&&a.getCookie("wt_ropc"))b="2";else{b="0";var f=x(a,"wt_ref","(.+?)(&|$)");""!==a.getCookie("wt_ref")?(b=a.wtEscape(a.getCookie("wt_ref")),a.setCookie("wt_ref","",-3600)):f?b=a.wtEscape(f):d?(b=a.wtEscape(d),d=!1):0<document.referrer.length&&(b=a.wtEscape(document.referrer));a.sentFullPixel?b="2":a.isOwnDomain(b)&&(b="1");a.referrerOncePerSession&&1<b.length&&a.setCookie("wt_ropc","1")}f=k.innerHeight;if(!f)try{f=document.documentElement.clientHeight}catch(h){}if(!f)try{f=
        document.body.clientHeight}catch(g){}"undefined"===typeof f&&(f=-1);var e;e=k.innerWidth;if(!e)try{e=document.documentElement.clientWidth}catch(m){}if(!e)try{e=document.body.clientWidth}catch(p){}"undefined"===typeof e&&(e=-1);f&&f>screen.height&&(f=screen.height);e&&e>screen.width&&(e=screen.width);c=c+b+(","+e+"x"+f);return c+=","+(navigator.javaEnabled()?"1":"0")};a.setReferrer=function(a){"string"===typeof a&&(d=a)}},x=function(a,d,c){var b=RegExp(d+"="+c);c=document.location.href;d=(new Date).getTime();
        b=b.exec(c);c=/wt_t=([\d]{13})/.exec(c);return b&&("undefined"!==typeof b[1]&&c&&"undefined"!==typeof c[1])&&parseInt(c[1])+9E5>d?a.wtUnescape(b[1]):!1},z=function(a,d,c,b){"1"!==a.cookie||(a.optOut||a.deactivatePixel)||a.firstParty();(c=c?c:"")||(c=a.formObject&&"noForm"!==d?"form":"link");"function"===typeof a.beforeUnloadPixel?a.beforeUnloadPixel():"form"===c&&a.executePlugin(a.getPluginConfig("form","before"));var f="";if(a.config.linkId&&(f+="&ct="+a.wtEscape(a.maxlen(a.wtUnescape(a.config.linkId),
    255)))){a.linktrackOut&&(f+="&ctx=1");var h=a.ccParams;"string"===typeof h&&""!==h&&(f+=h)}if(a.wtEp)if(a.wtEpEncoded)f+=a.wtEp;else if(h=a.wtEp,"string"===typeof h&&""!==h)for(var h=h.split(/;/),g=0;g<h.length;g++)if("undefined"!==typeof h[g]){var e=h[g].split(/\=/);a.checkSC("custom")&&(e[1]=a.decrypt(e[1]));e[1]=a.wtEscape(e[1]);f+="&"+e[0]+"="+e[1]}"noForm"!==d&&(f+=b.getFormTrackingData());""!==f&&(a.quicksend(a.wtEscape(a.contentId.split(";")[0])+",1,"+a.baseparams(),f),a.config.linkId="",a.ccParams=
        "",a.wtEp="");"function"===typeof a.afterUnloadPixel?a.afterUnloadPixel():"form"===c&&a.executePlugin(a.getPluginConfig("form","after"))},y=function(a){var d=[],c;for(c in a.safetagParameter){var b=c;if("executePluginFunction"===b)a.executePluginFunction+=a.safetagParameter[b],a.safetagParameter[b]="";else if("object"===typeof a.safetagParameter[b]){"object"!==typeof a[b]&&(a[b]={});for(var f in a.safetagParameter[b]){var h=f;a[b][h]=a.safetagParameter[b][h]}}else a[b]=a.safetagParameter[b],"linkTrack"!==
    b&&"heatmap"!==b&&"tabBrowsing"!==b&&"execCDB"!==b&&"execRTA"!==b||d.push(b)}for(c=0;c<d.length;c++)switch(d[c]){case "linkTrack":a.linkTrackInit();break;case "heatmap":a.heatmapTrackInit();break;case "tabBrowsing":a.startTabBrowsing();break;case "execCDB":a.startCDB();break;case "execRTA":a.startRTA()}a.safetagParameter.pixel=a},K=function(a){var d=function(b,c,d){!1!==b?b():a.executePlugin(a.getPluginConfig(c?c:"page",d))};a.getMediaCode=function(){if(a.mediaCode){var b=[],c=a.mediaCode.split(";"),
    d=0,g=[];a.mediaCodeValue&&(b=a.mediaCodeValue.split(";"));for(var e=0;e<c.length;e++){var m=a.urlParam(location.href,c[e],"");if(a.mediaCodeCookie){var k=!1,l=(a.trackId+"").split(",")[0],l="wt_mcc_"+(a.config.campaignAction?a.config.campaignAction.substring(0,1):"c")+"_"+l,n=a.getCookie(l),r;r=c[e]+"_"+m;for(var q=0,s=r.length,u=void 0,t=0;t<s;t++)u=r.charCodeAt(t),q=(q<<5)-q+u,q&=q;r=q>1E15-1?"0":q+"";-1===n.indexOf(","+r+",")&&m?(g.push(c[e]+a.wtEscape("="+m)),k=!0):d++;k&&(m="","eid"===a.mediaCodeCookie&&
    (m=2592E3),a.setCookie(l,n+","+r+",",m))}else"undefined"!==typeof b&&"undefined"!==typeof b[e]&&""!==b[e]?g.push(c[e]+a.wtEscape("="+b[e])):""!==m&&g.push(c[e]+a.wtEscape("="+m))}c.length===d&&0!==c.length&&g.push("ignore%3Dignore");a.config.campaignId=g.join(";")}};a.getExtLifeCycles=function(b,c,d){for(var g="",e={},m=b.split("|"),k=0;k<m.length;k++){for(var l=m[k].split(";"),n=0;n<l.length;n++)g=0===n?g+a.wtEscape(l[n]):g+l[n],g+=";";g=g.substr(0,g.length-1);g+="|"}g=g.substr(0,g.length-1);e.xlcl=
        a.wtEscape(b.split("|").length);e.xlct=a.wtEscape(c);"undefined"!==typeof d&&(e.xlcv=a.wtEscape(d));e.xlc=a.wtEscape(g);b="";for(var r in e)b+="&"+r+"="+e[r];return b};a.quicksend=function(b,c,d){!a.trackDomain||!a.trackId||a.deactivatePixel||a.deactivateRequest?a.deactivateRequest=!1:(d||(d="wt"+(a.fileSuffix?".pl":"")),"undefined"===typeof a.requestTimeout&&(a.requestTimeout=5),a.geid&&(c="&geid="+a.geid+c),a.cdbeid&&(c="&cdbeid="+a.cdbeid+c),"1"===a.cookie&&(c="&eid="+a.eid+"&one="+(a.cookieOne?
    "1":"0")+"&fns="+(a.forceNewSession?"1":"0")+c),"1"!==a.cookie&&(a.cookieEidTimeout&&(c="&cet="+a.cookieEidTimeout+c),a.cookieSidTimeout&&(c="&cst="+a.cookieSidTimeout+c)),0<a.pixelSampling&&(c+="&ps="+a.pixelSampling),c="&tz="+a.getTimezone()+c,c+="&pu="+a.wtEscape(document.location.href.split("#")[0]),b="//"+a.trackDomain+"/"+a.trackId+"/"+d+"?p="+a.version+","+b+c+"&eor=1",a.tabBrowsing?a.sendTabBrowsingPixel(b,d):!a.ignorePrerendering&&a.isChrome&&"undefined"!==typeof document.webkitHidden?("object"!==
    typeof a.prerendering&&(a.prerendering=[]),document.webkitHidden?(a.prerendering.push(b),a.registerEvent(document,"webkitvisibilitychange",function(){a.sendPrerendering()})):a.sendPixel(b,d)):a.sendPixel(b,d),"hm"!==d&&"hm.pl"!==d&&(a.cookieOne=!1,a.forceNewSession=!1,a.sentFullPixel=1))};a.sendPrerendering=function(){if(!document.webkitHidden){for(var b=0;b<a.prerendering.length;b++)a.sendPixel(a.prerendering[b]);a.prerendering=[]}};a.send=function(b,c,d){if("link"===c||"click"===c)a.config.linkId=
        b;a.config.contentId=a.config.contentId?a.config.contentId:a.contentId;(b=b?b:a.config.contentId)||(b="no_content");b=a.wtEscape(b)+",1,";b+=a.baseparams();var g;g=[];if(navigator.plugins&&"Microsoft Internet Explorer"!==navigator.appName)for(var e=0,m=navigator.plugins.length;e<m;e++){var p="",p="Shockwave Flash"===navigator.plugins[e].name?navigator.plugins[e].description:navigator.plugins[e].name;(p=a.plugInArray(a.plugins,p))&&g.push(p)}g=g.join("|");e="";if(a.paramFirst)for(m=a.paramFirst.split(";"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                p=0;p<m.length;p++){var l=a.getMappingParam(m[p]),n=l.mapping,l=l.index;n&&(l?a.config[n]&&("undefined"!==typeof a.config[n][l]&&a.config[n][l])&&(e+="&"+m[p]+"="+a.wtEscape(a.config[n][l])):a.config[n]&&(e+="&"+m[p]+"="+a.wtEscape(a.config[n])))}if("string"===typeof d&&""!==d)for(var r=d.split(/;/),q=0;q<r.length;q++){if("undefined"!==typeof r[q]){var s=r[q].split(/\=/);a.checkSC("custom")&&(s[1]=a.decrypt(s[1]));s[1]=a.wtEscape(s[1]);e+="&"+s[0]+"="+s[1]}}else{a.wtEpEncoded=!1;l=new a.PredefinedParameter;
        for(s in a.config)d=s+"",l.put(d,a.config[d]);var u=l.get("all");a.config.customParameter=a.mergeCustomParameter(a.config.customParameter,u.customParameter);s=a.checkCustomParameter(a.config.customParameter,"cp");a.config.customSessionParameter=a.mergeCustomParameter(a.config.customSessionParameter,u.customSessionParameter);d=a.checkCustomParameter(a.config.customSessionParameter,"cs");m=a.checkCustomParameter(a.config.customTimeParameter,"ce");p=a.checkCustomParameter(a.cdb,"cdb");a.config.customEcommerceParameter=
            a.mergeCustomParameter(a.config.customEcommerceParameter,u.customEcommerceParameter);n=a.checkCustomParameter(a.config.customEcommerceParameter,"cb");a.config.orderValue&&-1===a.paramFirst.indexOf("ov;")&&(e=a.checkSC("order")?e+("&ov="+a.wtEscape(a.decrypt(a.config.orderValue))):e+("&ov="+a.wtEscape(a.config.orderValue)));a.config.currency&&-1===a.paramFirst.indexOf("cr;")&&(e=a.checkSC("order")?e+("&cr="+a.wtEscape(a.decrypt(a.config.currency))):e+("&cr="+a.wtEscape(a.config.currency)));a.config.orderId&&
        -1===a.paramFirst.indexOf("oi;")&&(e+="&oi="+a.wtEscape(a.config.orderId));a.config.product&&(-1===a.paramFirst.indexOf("ba;")&&(e+="&ba="+a.wtEscape(a.config.product)),a.config.productCost&&-1===a.paramFirst.indexOf("co;")&&(e+="&co="+a.wtEscape(a.config.productCost)),a.config.productQuantity&&-1===a.paramFirst.indexOf("qn;")&&(e+="&qn="+a.wtEscape(a.config.productQuantity)),a.config.productCategory=a.mergeCustomParameter(a.config.productCategory,u.productCategory),e+=a.checkCustomParameter(a.config.productCategory,
        "ca"),a.config.productStatus&&-1===a.paramFirst.indexOf("st;")&&(e+="&st="+a.wtEscape(a.config.productStatus)));var t=x(a,"wt_cd","(.+?)(&|$)");a.config.customerId||(a.config.customerId=t);a.config.customerId&&-1===a.paramFirst.indexOf("cd;")&&(e+="&cd="+a.wtEscape(a.config.customerId));a.config.crmCategory=a.mergeCustomParameter(a.config.crmCategory,u.crmCategory);e+=a.checkCustomParameter(a.config.crmCategory,"vc");null===l.get("birthday")&&(a.config.birthdayJ&&a.config.birthdayM&&a.config.birthdayD)&&
        l.put("birthday",a.config.birthdayJ+a.config.birthdayM+a.config.birthdayD);null!==l.get("telefon")&&l.put("telefon",l.get("telefon").replace(/\W|_/g,""));a.config.urmCategory=a.mergeCustomParameter(a.config.urmCategory,u.urmCategory);e+=a.checkCustomParameter(a.config.urmCategory,"uc");a.browserLang&&(e+="&la="+a.wtEscape(a.browserLang));a.config.contentGroup=a.mergeCustomParameter(a.config.contentGroup,u.contentGroup);e+=a.checkCustomParameter(a.config.contentGroup,"cg");l="";if(a.config.campaignId){var t=
            a.config.campaignAction?a.config.campaignAction.substring(0,1):"c",v=t+"_"+a.config.campaignId;v in a.sentCampaignIds?a.config.campaignId="ignore%3Dignore":a.sentCampaignIds[v]=!0;-1===a.paramFirst.indexOf("mc;")&&(e+="&mc="+a.wtEscape(a.config.campaignId));-1===a.paramFirst.indexOf("mca;")&&(e+="&mca="+t)}a.config.customCampaignParameter=a.mergeCustomParameter(a.config.customCampaignParameter,u.customCampaignParameter);l+=a.checkCustomParameter(a.config.customCampaignParameter,"cc");a.trackingSwitchMediaCode&&
        (e+="&tmc="+a.wtEscape(a.trackingSwitchMediaCode));a.trackingSwitchMediaCodeValue&&(e+="&tmcv="+a.wtEscape(a.trackingSwitchMediaCodeValue));a.trackingSwitchMediaCodeTimestamp&&(e+="&tmct="+a.wtEscape(a.trackingSwitchMediaCodeTimestamp));"object"===typeof k.wt_ts&&("undefined"!==typeof k.wt_ts.trackingSwitchMediaCode&&(e+="&tmc="+a.wtEscape(k.wt_ts.trackingSwitchMediaCode)),"undefined"!==typeof k.wt_ts.trackingSwitchMediaCodeValue&&(e+="&tmcv="+a.wtEscape(k.wt_ts.trackingSwitchMediaCodeValue)),"undefined"!==
        typeof k.wt_ts.trackingSwitchMediaCodeTimestamp&&(e+="&tmct="+a.wtEscape(k.wt_ts.trackingSwitchMediaCodeTimestamp)));u="";"undefined"!==typeof k.wt_vt&&(q=k.wt_vt);"undefined"===typeof q&&(q=a.urlParam(location.href,"wt_vt",!1));if(q)for(t=a.getCookie("wt_vt").split(";"),v=0;v<t.length;v++)-1!==t[v].indexOf(q+"v")&&(u="&wt_vt="+t[v].split("t")[0].split("v")[1]);u&&(e+=u);a.config.internalSearch&&-1===a.paramFirst.indexOf("is;")&&(e+="&is="+a.wtEscape(a.maxlen(a.wtUnescape(a.config.internalSearch),
        255)));if(a.config.dynamicParameters)for(r in a.config.dynamicParameters)q=r+"",a.config.dynamicParameters[q]&&(e="object"===typeof a.config.dynamicParameters[q]?e+a.checkCustomParameter(a.config.dynamicParameters,q):e+("&"+r+"="+a.wtEscape(a.config.dynamicParameters[q])));s&&(e+=s);l&&(e+=l);m&&(e+=m);n&&(e+=n);d&&(e+=d);p&&(e+=p);a.config.customSid&&(e+="&csid="+a.config.customSid);a.config.customEid&&(e+="&ceid="+a.config.customEid);a.config.xwtip&&(e+="&X-WT-IP="+a.wtEscape(a.config.xwtip));a.config.xwtua&&
        (e+="&X-WT-UA="+a.wtEscape(a.config.xwtua));a.config.xwtrq&&(e+="&X-WT-RQ="+a.wtEscape(a.config.xwtrq));a.xwteid&&(e+="&X-WT-EID="+a.wtEscape(a.xwteid),a.xwteid=!1);a.config.xwtstt&&(e+="&X-WT-STT="+a.wtEscape(a.config.xwtstt));!a.sentFullPixel&&a.firstVisitContact&&(e+="&fvc="+a.firstVisitContact);!a.sentFullPixel&&a.lastVisitContact&&(e+="&lvc="+a.lastVisitContact)}a.config.linkId&&a.config.customClickParameter&&(e+=a.checkCustomParameter(a.config.customClickParameter[a.config.linkId]?a.config.customClickParameter[a.config.linkId]:
    a.config.customClickParameter,"ck"),a.ccParams=!1);a.config.xlc&&a.config.xlct&&(""!==a.config.xlc||""!==a.config.xlct)&&(r="",r=a.config.xlcv?a.getExtLifeCycles(a.config.xlc,a.config.xlct,a.config.xlcv):a.getExtLifeCycles(a.config.xlc,a.config.xlct),e+=r);a.config.contentId||a.config.linkId||(a.config.contentId=a.contentId,a.config.linkId="wt_ignore");a.config.linkId?(a.wtEp=e,a.wtEpEncoded=!0,z(a,"noForm",c)):("1"===a.cookie?a.cookieOne&&(e+="&np="+a.wtEscape(g)):e+="&np="+a.wtEscape(g),a.quicksend(b,
    e))};var c=function(){a.safetagTimeoutStarted=!0;var b=(new Date).getTime()-a.startSafetagTimeoutDate;if(a.safetagInProgress&&b<a.safetag.timeout)k.setTimeout(function(){c()},5);else{a.safetagTimeoutStarted=!1;a.safetagInProgress=!1;b>a.safetag.timeout&&(a.xwtstt=a.safetag.timeout+"");for(b=0;b<a.saveSendinfoArguments.length;b++){var d=a.saveSendinfoArguments[b];a.sendinfo(d[0],d[1],d[2],d[3])}a.saveSendinfoArguments=[]}};a.sendinfo=function(b,f,h,g){h=h?h:"page";-1===location.href.indexOf("fb_xd_fragment")&&
    (a.safetag&&y(a),a.config="object"===typeof b?b:a.getConfig(),a.safetagInProgress?(b?a.saveSendinfoArguments.push([a.config,f,h,g]):a.saveSendinfoArguments.push([!1,f,h,g]),a.safetagTimeoutStarted||(a.startSafetagTimeoutDate=(new Date).getTime(),k.setTimeout(function(){c()},5))):(a.config.linkId&&(h="click",f||(f=a.config.linkId)),d(a.beforeSendinfoPixel,h,"before"),a.safetag&&y(a),a.optOut||a.deactivatePixel||("1"===a.cookie?a.firstParty():a.xwteid=x(a,"wt_eid","([\\d]{19})")),a.config.campaignId||
    (!a.mediaCode||"page"!==h||a.config.linkId)||a.getMediaCode(),""===a.contentId&&""===f||a.send(f,h,g),d(a.afterSendinfoPixel,h,"after")))}},L=function(a){for(var d=[D,E,F,G,H,I,J,K],c=0;c<d.length;c++)d[c](a)},M=function(a){a.setProperty("paramFirst","");a.jsonPara={ck:["customClickParameter",{}],cp:["customParameter",{}],cs:["customSessionParameter",{}],ce:["customTimeParameter",{}],cb:["customEcommerceParameter",{}],vc:["crmCategory",{}],uc:["urmCategory",{}],ca:["productCategory",{}],cc:["customCampaignParameter",
            {}],cg:["contentGroup",{}],ct:["linkId",""],ov:["orderValue",""],cr:["currency",""],oi:["orderId",""],ba:["product",""],co:["productCost",""],qn:["productQuantity",""],st:["productStatus",""],cd:["customerId",""],is:["internalSearch",""],mc:["campaignId",""],mca:["campaignAction",""]};a.checkBrowser=function(){a.isIE=-1!==navigator.appName.indexOf("Microsoft");a.isIE||(a.isOpera=-1!==navigator.appName.indexOf("Opera"),a.isOpera||(a.isSafari=-1!==navigator.vendor.toLowerCase().indexOf("apple"),a.isChrome=
    -1!==navigator.vendor.toLowerCase().indexOf("google"),a.isSafari||a.isChrome||(a.isFirefox=-1!==navigator.userAgent.toLowerCase().indexOf("firefox"))))};a.generateDefaultConfig("trackId trackDomain domain forceHTTPS secureConfig beforeSendinfoPixel afterSendinfoPixel beforeUnloadPixel afterUnloadPixel ignorePrerendering plugins trackingSwitchMediaCode trackingSwitchMediaCodeValue trackingSwitchMediaCodeTimestamp isIE isOpera isSafari isChrome isFirefox wtEpEncoded fileSuffix dynamicParameters xwtip xwtua xwtrq config xwteid xwtstt customTimeParameter sentFullPixel wtEp".split(" "));
        a.plugins||(a.plugins="Adobe Acrobat;Windows Media Player;Shockwave Flash;RealPlayer;QuickTime;Java;Silverlight".split(";"));"string"===typeof a.plugins&&(a.plugins=a.plugins.split(";"));a.browserLang=!1;"string"===typeof navigator.language?a.browserLang=navigator.language.substring(0,2):"string"===typeof navigator.userLanguage&&(a.browserLang=navigator.userLanguage.substring(0,2));a.checkBrowser()},N=function(a){a.url2contentId=function(a){if(!a)return"no_content";a=/\/\/(.*)/.exec(a);return 1>a.length?
    "no_content":a[1].split("?")[0].replace(/\./g,"_").replace(/\//g,".").replace(/\.{2,}/g,".").toLowerCase().split(";")[0]};a.generateDefaultConfig("contentId contentGroup internalSearch numberSearchResults errorMessages npsScore npsScoreFeedback paywall articleTitle pageMainCategory pageSubCategory pageAuthor contentTags pageTitle pageType pageLength daysSincePublication testVariant testExperiment customParameter".split(" "));a.contentId=a.contentId?a.contentId:a.url2contentId(document.location.href)},
    O=function(a){"undefined"===typeof a.safetag&&(a.safetag=!1);"undefined"===typeof a.safetagInProgress&&(a.safetagInProgress=!1);"undefined"===typeof a.safetagParameter&&(a.safetagParameter={});"undefined"===typeof a.update&&(a.update=function(){});a.saveSendinfoArguments=[];a.safetagTimeoutStarted=!1},P=function(a){a.generateDefaultConfig(["loginStatus","pixelVersion","trackingPlatform","customSessionParameter","forceNewSession"])},Q=function(a){a.generateDefaultConfig("customEcommerceParameter orderValue currency orderId product productCost productQuantity productCategory productStatus couponValue productLabel productMainCategory productSubCategory productManufacturer paymentMethod productShortDescription productLongDescription shippingService shippingSpeed shippingCosts grossMargin orderStatus productVariant productSoldOut".split(" "))},
    R=function(a){a.generateDefaultConfig("crmCategory urmCategory customerId customSid customEid xlc xlct xlcv paywallUser email emailRID emailOptin firstName lastName telefon gender birthday birthdayJ birthdayM birthdayD country city postalCode street streetNumber validation".split(" "))},S=function(a){a.setProperty("formAttribute","name");a.setProperty("formFieldAttribute","name");a.setProperty("formValueAttribute","value");a.setProperty("formFieldDefaultValue",{});a.setProperty("multipleFormArray",
        []);a.generateDefaultConfig("form formFullContent formAnonymous gatherFormsP formObject formName formFocus formSubmit formPathAnalysis".split(" "))},T=function(a){a.setProperty("linkTrackAttribute","name");a.setProperty("delayLinkTrackTime",200);a.generateDefaultConfig("linkId linkTrack linkTrackParams linkTrackPattern linkTrackReplace linkTrackDownloads linkTrackIgnorePattern customClickParameter delayLinkTrack noDelayLinkTrackAttribute linktrackOut linktrackNamedlinksOnly ccParams".split(" "))},
    U=function(a){a.sentCampaignIds={};a.setProperty("campaignAction","click");a.generateDefaultConfig("mediaCode mediaCodeValue mediaCodeCookie campaignId customCampaignParameter referrerOncePerSession".split(" "))},V=function(a){a.cdb={};a.cdbData=[]},W=function(a,d,c){a.getConfig=function(b){var c={},d;for(d in a)c[d]=b?!1:a[d];return c};a.setProperty=function(b,f){a[b]=f;"undefined"!==typeof d[b]?a[b]=d[b]:"undefined"!==typeof c[b]&&(a[b]=c[b])};a.generateDefaultConfig=function(b){for(var c=0;c<b.length;c++)a.setProperty(b[c],
        !1)};(function(){for(var b=[M,N,O,P,Q,R,S,T,U,V],f=0;f<b.length;f++)b[f](a,d,c)})()},y=function(a){var d=[],c;for(c in a.safetagParameter){var b=c;if("executePluginFunction"===b)a.executePluginFunction+=a.safetagParameter[b],a.safetagParameter[b]="";else if("object"===typeof a.safetagParameter[b]){"object"!==typeof a[b]&&(a[b]={});for(var f in a.safetagParameter[b]){var h=f;a[b][h]=a.safetagParameter[b][h]}}else a[b]=a.safetagParameter[b],"linkTrack"!==b&&"heatmap"!==b&&"tabBrowsing"!==b&&"execCDB"!==
    b&&"execRTA"!==b||d.push(b)}for(c=0;c<d.length;c++)switch(d[c]){case "linkTrack":a.linkTrackInit();break;case "heatmap":a.heatmapTrackInit();break;case "tabBrowsing":a.startTabBrowsing();break;case "execCDB":a.startCDB();break;case "execRTA":a.startRTA()}a.safetagParameter.pixel=a},X=function(a){a.pageCounter=0;a.clickCounter=0;a.linkCounter=0;a.formCounter=0;a.heatmapCounter=0;a.configCounter=0;a.plugin={};a.setProperty("executePluginFunction","");a.getRequestCounter=function(d,c){var b=0;"after"!==
    c&&b++;return"undefined"!==typeof a[d+"Counter"]?(a[d+"Counter"]+=b,a[d+"Counter"]):0};a.getPluginConfig=function(d,c){return{instance:a,mode:d,type:c,requestCounter:a.getRequestCounter(d,c)}};a.executePlugin=function(d,c){if(!a.executePluginFunction||"string"!==typeof a.executePluginFunction)return!1;var b=c?c:{};a.epf=!1;for(var f=a.executePluginFunction.split(";"),h=0;h<f.length;h++)f[h]&&"function"===typeof k[f[h]]&&(a.epf=k[f[h]],a.epf(d,b));return!1!==a.epf};a.triggerConfigPlugins=function(d){"undefined"!==
    typeof a.safetag&&a.safetag&&y(a);a.config="object"===typeof d?d:a.getConfig();a.executePlugin(a.getPluginConfig("config","before"));"undefined"!==typeof a.safetag&&a.safetag&&y(a);a.executePlugin(a.getPluginConfig("config","after"))}},Y=function(a){a.setProperty("cookie","3");a.setProperty("updateCookie",!0);a.setProperty("cookieSecure",!1);a.setProperty("cookieEidTimeout",!1);a.setProperty("cookieSidTimeout",!1);var d=function(c,b,d,h){c=a.wtEscape(c)+"="+a.wtEscape(b);c=c+(";domain="+d)+";path=/";
        h&&(c+=";expires="+a.getExpiryDate(h));a.cookieSecure&&(c+=";secure");document.cookie=c};a.getExpiryDate=function(a){var b=new Date,d=b.getTime();b.setTime(d+6E4*a);return b.toUTCString()};a.setCookie=function(c,b,f){var h=document.location.hostname;if(-1===h.search(/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$/))for(var g=h.split("."),e=g[g.length-1],m=g.length-2;0<=m;m--)if(e=g[m]+"."+e,d(c,b,e,f),a.getCookie(c)===b)return;d(c,b,h,f)};a.getCookie=function(c){for(var b=document.cookie.split(";"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     d=0;d<b.length;d++){var h=b[d].substr(0,b[d].indexOf("=")),g=b[d].substr(b[d].indexOf("=")+1),h=h.replace(/^\s+|\s+$/g,"");if(h===c)return a.wtUnescape(g)}return""}},Z=function(a){a.cookieManager=function(a,c,b,f){this.name=a;this.keySeperator="~";this.fieldSeparator="#";this.durationSeperator="|";this.found=!1;this.expires=c?c:!1;this.accessPath=b?b:"/";this.secure=f?f:!1;this.rawValue="";this.fields=[];this.fieldsDuration=[];var h=function(a){try{return decodeURIComponent(a)}catch(b){return k.unescape(a)}},
        g=function(a){try{return encodeURIComponent(a)}catch(b){return k.escape(a)}};this.read=function(){this.rawValue=null;this.found=!1;for(var a=document.cookie.split(";"),b=0;b<a.length;b++){var c=a[b].substr(0,a[b].indexOf("=")),d=a[b].substr(a[b].indexOf("=")+1),c=c.replace(/^\s+|\s+$/g,"");c===this.name&&(this.rawValue=d,this.found=!0)}if(null!==this.rawValue){a=b=0;do a=this.rawValue.indexOf(this.fieldSeparator,b),-1!==a&&(b=this.rawValue.substring(b,a).split(this.durationSeperator),c=b[0].split(this.keySeperator),
        this.fields[c[0]]=h(c[1]),this.fieldsDuration[c[0]]=parseInt(h(b[1])),b=a+1);while(-1!==a&&a!==this.rawValue.length-1)}return this.found};this.getSize=function(){var a=(new Date).getTime(),b="",c;for(c in this.fields){var d=c+"";this.fieldsDuration[d]>=a&&(b+=g(d)+this.keySeperator+g(this.fields[d])+this.durationSeperator+g(this.fieldsDuration[d])+this.fieldSeparator)}return b.length};this.write=function(){var a=(new Date).getTime(),b=!0,c=this.name+"=",d;for(d in this.fields){var f=d+"";this.fieldsDuration[f]>=
    a&&(c+=g(f)+this.keySeperator+g(this.fields[f])+this.durationSeperator+g(this.fieldsDuration[f])+this.fieldSeparator,b=!1)}a=b?-99999:this.expires;""!==a&&"number"===typeof a&&(b=new Date,b.setTime((new Date).getTime()+864E5*a),c+="; expires="+b.toGMTString());null!==this.accessPath&&(c+="; PATH="+this.accessPath);a=location.hostname;-1===a.search(/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$/)&&(a=location.hostname.split("."),a=a[a.length-2]+"."+a[a.length-1]);b="";this.secure&&(b=";secure");
        document.cookie=c+("; DOMAIN="+a)+b};this.remove=function(){this.expires=-10;this.write();return this.read()};this.get=function(a){var b=(new Date).getTime();return this.fieldsDuration[a]>=b?this.fields[a]:""};this.set=function(a,b,c,d,f){c=c?c:31536E3;d=d?d:"last";var h=(new Date).getTime();if("first"===d&&""!==this.fields[a]&&null!==this.fields[a]&&this.fieldsDuration[a]>=h)return this.fields[a];this.fields[a]=b;this.fieldsDuration[a]=h+1E3*parseInt(c);f||this.write();return b};this.prepare=function(a,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   b,c,d){return this.set(a,b,c,d,!0)};this.read()}},$=function(a,d,c){Y(a,d,c);Z(a)},aa=function(a){a.setProperty("pixelSampling",!1);a.setPixelSampling=function(d){d=d?d:a.pixelSampling;for(var c=a.trackId.split(",")[0],b=a.getCookie("wt3_sample").split(";"),f=!1,h=0;h<b.length;h++)-1!==b[h].indexOf(c+"|"+d)?f=!0:-1!==b[h].indexOf(c+"|")&&(b[h]="");h=6;a.cookieEidTimeout&&(h=a.cookieEidTimeout);f?(b=b.join(";"),a.setCookie("wt3_sample",b,43200*h)):(Math&&Math.random&&0===parseInt(Math.random()*d)?
        b.push(c+"|"+d+"|1"):b.push(c+"|"+d+"|0"),a.setCookie("wt3_sample",b.join(";"),43200*h),b=a.getCookie("wt3_sample"));-1===b.indexOf(c+"|"+d+"|1")&&(a.deactivatePixel=!0)};a.pixelSampling&&!a.optOut&&a.setPixelSampling()},ba=function(a,d,c){a.deactivatePixel=!1;a.optOut=!1;a.setProperty("optoutName","webtrekkOptOut");a.optOut=""!==a.getCookie(a.optoutName);a.optOut&&(a.deactivatePixel=!0);aa(a,d,c)},ca=function(a){a.deactivateRequest=!1;a.completeRequest=!1;a.setProperty("simulatedRequestTimeout",
        500);a.setProperty("replaceMutatedVowel",!1);a.setProperty("requestLimitAmount",1E3);a.setProperty("requestLimitTime",1800);a.setProperty("maxRequestLength",7168);var d=!1;a.sendPixel=function(c,b){var f=c,h=-1!==f.indexOf("&ct=")?"link":-1!==f.indexOf("&fn=")?"form":-1!==f.indexOf("&mi=")?"media":-1!==f.indexOf("/hm")?"heatmap":-1!==f.indexOf("/cdb")||-1!==f.indexOf("/fbc")?"cdb":-1!==f.indexOf("/ce")?"independent":-1!==f.indexOf("/re")?"redirect":"page",g;a:{var e=a.trackId.split(",")[0],k=a.getCookie("wt_rla").split(";");
        g={};for(var p=0,l=k.length;p<l;p++){var n=k[p].split(",");if(3<=n.length){var r=parseInt(n[1]),q=parseInt(n[2]);g[n[0]]={amount:isNaN(r)?0:r,time:isNaN(q)?(new Date).getTime():q}}}"undefined"===typeof g[e]&&(g[e]={amount:0,time:(new Date).getTime()});k=(new Date).getTime();if(k-g[e].time>1E3*a.requestLimitTime)d=!1,g[e]={amount:0,time:k};else if(g[e].amount===a.requestLimitAmount-1&&(d=!0),g[e].amount>=a.requestLimitAmount){g=!0;break a}if("link"===h||"page"===h||"form"===h){g[e].amount++;var e=
            [],s;for(s in g)e.push(s+","+g[s].amount+","+g[s].time);a.setCookie("wt_rla",e.join(";"),86400)}g=!1}if(!g){if(a.replaceMutatedVowel){g=[[/%C3%84/g,"ae"],[/%C3%A4/g,"ae"],[/%C4/g,"ae"],[/%E4/g,"ae"],[/%C3%96/g,"oe"],[/%C3%B6/g,"oe"],[/%D6/g,"oe"],[/%F6/g,"oe"],[/%C3%9C/g,"ue"],[/%C3%BC/g,"ue"],[/%DC/g,"ue"],[/%FC/g,"ue"],[/%C3%9F/g,"ss"],[/%DF/g,"ss"]];s=0;for(e=g.length;s<e;s++)f=f.replace(g[s][0],g[s][1]);f=f.toLowerCase()}a.completeRequest=f.split("?")[1];f=a.maxlen(f,a.maxRequestLength);d&&(f+=
        "&rla="+a.requestLimitAmount+"%7C"+a.requestLimitTime);!a.isFirefox||"link"!==h&&"form"!==h?a.sendPixelImage(f,b,h):a.sendPixelElement(f,b,h)}};a.sendPixelImage=function(c,b,d){var h="https:"===k.document.location.protocol?"https:":"http:";a.forceHTTPS&&(h="https:");0!==c.search(/https:|http:/)&&(c=h+c);if("hm"===b||"hm.pl"===b)c+="&hm_ts="+(new Date).getTime();"function"!==typeof k.Image&&(k.Image=function(){return document.createElement("img")});b=new k.Image;(function(b,c,d){var f=!1,h=function(d,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               h){if(!f){f=!0;var k=(new Date).getTime()-c;b&&d&&a.executePlugin({instance:a,mode:h,type:d,requestCounter:0},{status:d,time:k,request:b.src,item:b})}};b.onerror=function(){h("error",d)};b.onload=function(){h("success",d)};k.setTimeout(function(){h("timeout",d)},a.simulatedRequestTimeout)})(b,(new Date).getTime(),d);b.src=c};a.createPixelElement=function(a){a=a.replace(/'/g,"%27");var b=document.createElement("div");b.style.width="0px";b.style.height="0px";b.style.backgroundImage='url("'+a+'")';k.setTimeout(function(){b.parentElement.removeChild(b)},
        5E3);return b};a.sendPixelElement=function(c,b,d){var h="https:"===k.document.location.protocol?"https:":"http:";a.forceHTTPS&&(h="https:");0!==c.search(/https:|http:/)&&(c=h+c);if("hm"===b||"hm.pl"===b)c+="&hm_ts="+(new Date).getTime();if("undefined"===typeof a.sendPixelObject||null===a.sendPixelObject)(b=document.getElementById("webtrekk-image"))&&null!==b?a.sendPixelObject=b:(a.sendPixelObject=document.createElement("div"),a.sendPixelObject.id="webtrekk-image",a.sendPixelObject.style.width="0px",
        a.sendPixelObject.style.height="0px",a.sendPixelObject.style.overflow="hidden",b=null,"object"===typeof document.body?b=document.body:"object"===typeof document.getElementsByTagName("body")[0]&&(b=document.getElementsByTagName("body")[0]),b&&null!==b?b.appendChild(a.sendPixelObject):(a.sendPixelObject=null,a.sendPixelImage(c,"wt"+(a.fileSuffix?".pl":""),d)));null!==a.sendPixelObject&&a.sendPixelObject.appendChild(a.createPixelElement(c))}},x=function(a,d,c){var b=RegExp(d+"="+c);c=document.location.href;
        d=(new Date).getTime();b=b.exec(c);c=/wt_t=([\d]{13})/.exec(c);return b&&("undefined"!==typeof b[1]&&c&&"undefined"!==typeof c[1])&&parseInt(c[1])+9E5>d?a.wtUnescape(b[1]):!1},A=function(a){var d=a.trackId.split(",")[0],c="number"===typeof a.cookieEidTimeout?a.cookieEidTimeout:6,b=a.generateEid(),f="",h="",g=[],e=-1,m="",p=!1,l=b,n=!1,r=function(){c?a.setCookie("wt3_eid",g.join(";"),43200*c):a.setCookie("wt3_eid",g.join(";"))},q=function(b,c){for(var d=!1,f=a.getCookie("wt3_eid").split(";"),h=0,e=
        f.length;h<e;h++)if(-1!==f[h].indexOf(c+"|")){d=!0;f[h]=c+"|"+b;break}d||f.push(c+"|"+b);g=f;r()},s=function(a){if(a&&"2"===a.substring(0,1)){a=parseInt(a.substring(1,11)+"000");a=new Date(a);var b=a.getFullYear()+"",b=b+(10>a.getMonth()+1?"0":""),b=b+(a.getMonth()+1),b=b+(10>a.getDate()?"0":""),b=b+a.getDate(),b=b+(10>a.getHours()?"0":""),b=b+a.getHours(),b=b+(10>a.getMinutes()?"0":"");return b+=a.getMinutes()}return""};this.init=function(){g=a.getCookie("wt3_eid").split(";");for(var c=0;c<g.length;c++)if(-1!==
        g[c].indexOf(d+"|")){e=c;h=g[c];m=h.replace(d+"|","").split("#")[0];-1!==h.indexOf("#")&&(l=h.replace(d+"|","").split("#")[1]);break}f=x(a,"wt_eid","([\\d]{19})");"string"===typeof k.webtrekkApplicationEverId&&(f=k.webtrekkApplicationEverId);m?(f&&(g[e]=d+"|"+f,m=f,a.updateCookie=!0),"undefined"!==typeof k.wt_mcp_eid&&(p=!0),-1===g[e].indexOf("#")?g[e]+="#"+b:g[e]=h.replace(/#[0-9]{19}/g,"#"+b),a.updateCookie?r():n=l=!1):("string"===typeof k.wt_mcp_eid&&-1!==k.wt_mcp_eid.indexOf(d+"|")?(m=k.wt_mcp_eid.replace(d+
        "|",""),p=!0):f?m=f:(m=a.generateEid(),p=!0),g.push(d+"|"+m+"#"+b),r());a.updateCookie&&(l=s(l),n=s(m))};this.getId=function(){var b;if(b=a.validateEverId)b=m.replace(/^\d((\d){10})\d+$/,"$1"),b=!(1089676800<parseInt(b));b&&(m=a.generateEid(),q(m,d));return m};this.setId=function(a,b){q(a,b)};this.getUrlId=function(){return f};this.getLastVisitContact=function(){return l};this.getFirstVisitContact=function(){return n};this.getCookieOne=function(){return p}},B=function(a){var d=a.trackId.split(",")[0],
        c=[],b="";this.init=function(){c=a.getCookie("wt3_sid").split(";");for(var f=0;f<c.length;f++)if(-1!==c[f].indexOf(d)){b=c[f];break}b||c.push(d);a.setCookie("wt3_sid",c.join(";"))};this.getId=function(){return b};this.setId=function(b){for(var c=!1,d=a.getCookie("wt3_sid").split(";"),e=0,k=d.length;e<k;e++)if(-1!==d[e].indexOf(b)){c=!0;break}c||d.push(b);a.setCookie("wt3_sid",d.join(";"))}},ea=function(a){a.geid=!1;a.setProperty("execRTA",!0);var d=!1,c=function(){d=!0;if(!a.deactivatePixel){"string"!==
    typeof a.execRTA&&(a.execRTA=document.location.protocol+"//cdn.wbtrk.net/js/geid.min.js");var b=a.getCookie("wt_geid");b?"68934a3e9455fa72420237eb"!==b&&(a.geid=b):a.loadAsynchron(a.execRTA,"wt_geid",function(a,b){a&&k.wt_geid(b,k)},2E3)}};a.execRTA&&c();a.startRTA=function(){d||(a.execRTA=a.execRTA?a.execRTA:!0,c())}},fa=function(a){var d="https:"===k.document.location.protocol?"https:":"http:",c=!1,b=function(a){var b=document.createElement("canvas"),c=null;try{c=b.getContext(a)}catch(d){}return c&&
        null!==c},f=function(a,b){var c=document.createElement("img");c.crossOrigin="use-credentials";(function(a,b){var c=!1,d=function(d,f){if(!c){c=!0;if(d){var h=document.createElement("canvas"),e=h.getContext("2d");h.height=a.height;h.width=a.width;e.drawImage(a,0,0);try{var g=e.getImageData(0,0,6,1).data;return b(g)}catch(k){return b([],"5")}}return b([],f)}return 0};a.onerror=function(){d(!1,"4")};a.onload=function(){d(!0)};k.setTimeout(function(){d(!1,"3")},2E3)})(c,b);c.src=d+"//"+a},h=function(a){for(var b=
        "",c=0,d;c<a.length;c++)d=a[c].toString(16),2>d.length&&(d="0"+d),b+=d,2===c%4&&c++;b=b.substr(0,b.length-4);return"string"===typeof b&&-1!==b.search(/^[0-9a-f]{32}$/)&&-1===b.search(/^[f]{32}$/)?b:""},g=function(b){"1"===b?a.setCookie("wt_cdbeid",b,15):a.setCookie("wt_cdbeid",b)},e=function(b){a.sendPixel(b,"")},m=function(b){("1"!==a.cookie||"1"===a.cookie&&a.eid)&&0<a.pageCounter?k.setTimeout(function(){b()},300):k.setTimeout(function(){m(b)},50)},p=function(b){m(function(){var c;if("1"===a.cookie)c=
        "//fbc.wcfbc.net/v1/fbc"+("?p="+a.version+",0"),c+="&eid="+a.wtEscape(a.eid),c+="&acc="+a.wtEscape(a.trackId),c+="&t="+(new Date).getTime(),c+="&err="+b,e(c);else for(var f=a.trackId.split(","),h=0,g=f.length;h<g;h++){var t=d+"//fbc.wcfbc.net/v1/fbc",t=t+("?p="+a.version+",0"),t=t+("&acc="+a.wtEscape(f[h])),t=t+("&t="+(new Date).getTime()),t=t+("&err="+b);c="//";c+=a.trackDomain+"/"+a.trackId+"/cc";c+="?a=r&c=wteid_"+f[h];c+="&t="+a.wtEscape(t);e(c)}})},l=function(){c=!0;if(!a.deactivatePixel){var d=
        a.getCookie("wt_cdbeid");d&&-1!==d.search(/^[0-9a-f]{32}$/)&&(a.cdbeid=d);d||(a.useCDBCache&&!a.isIE&&b("2d")?("string"!==typeof a.useCDBCache&&(a.useCDBCache="fbc.wcfbc.net/v1/fbc"),f(a.useCDBCache,function(b,c){var d=h(b);d?(g(d),m(function(){var b="//"+a.trackDomain+"/"+a.trackId+"/cdb",b=b+("?p="+a.version+",0,,,,,"+(new Date).getTime()+",,,");a.eid&&(b+="&eid="+a.eid);b+="&cdbeid="+d;e(b)})):(g("1"),p(c?c:"6"))})):(d="",a.useCDBCache&&a.isIE?d="1":a.useCDBCache&&!b("2d")&&(d="2"),g("1"),p(d)))}};
        a.cdbeid=!1;a.setProperty("execCDB",!0);a.setProperty("useCDBCache",!1);a.startCDB=function(){c||(a.execCDB=!0,l())};a.execCDB&&l()},ga=function(a,d,c){a.eid=!1;a.firstVisitContact=!1;a.lastVisitContact=!1;a.cookieOne=!1;a.setProperty("globalVisitorIds",!1);a.setProperty("validateEverId",!1);a.zeroPad=function(a,c){for(var d="",g=0;g<=c;g++)d+="0";d+=a;return d.substring(d.length-c,d.length)};a.generateEid=function(){var b=Math.floor((new Date).getTime()/1E3);1089676800>b&&(b="3"+a.zeroPad(Math.floor(1E4*
        Math.random()),4)+a.zeroPad(Math.floor(1E5*Math.random()),5));return"2"+a.zeroPad(b,10)+a.zeroPad(Math.floor(1E8*Math.random()),8)};a.setEverId=function(b,c){b&&("string"===typeof b&&-1!==b.search(/^[0-9]{19}$/))&&(c&&"string"===typeof b||(c=a.trackId.split(",")[0]),(new A(a)).setId(b,c),(new B(a)).setId(c))};a.firstParty=function(){var b=new A(a);b.init();var c=new B(a);c.init();a.eid=b.getId();a.cookieOne=b.getCookieOne();c.getId()||(b.getId()!==b.getUrlId()&&(a.forceNewSession=!0),a.firstVisitContact=
        b.getFirstVisitContact(),a.lastVisitContact=b.getLastVisitContact())};a.globalVisitorIds&&(d.execRTA=!0,d.execCDB=!0);ea(a,d,c);fa(a,d,c)},ha=function(a){a.overlayOn="1"===a.urlParam(a.wtHref(),"wt_overlay","0")||"1"===a.getCookie("wt_overlay");var d=function(){"undefined"!==typeof k.wt_overlay?k.setTimeout(function(){k.wt_overlay()},1E3):("undefined"===typeof k.wt_overlay_retry&&(k.wt_overlay_retry=0),k.wt_overlay_retry++,60>k.wt_overlay_retry&&k.setTimeout(function(){d()},1E3))};"0"===a.urlParam("wt_overlay")&&
    (a.overlayOn=!1,a.setCookie("wt_overlay","",-3600));a.overlayOn&&!a.disableOverlayView&&(a.setCookie("wt_overlay","1"),a.startHeatmapOrOverlay("overlay",d))},ia=function(a){a.heatmapOn="1"===a.urlParam(a.wtHref(),"wt_heatmap","0");a.setProperty("heatmapRefpoint","wt_refpoint");a.setProperty("heatmap",!1);var d=function(b){var c,d,g=document.getElementById(a.heatmapRefpoint);d=g&&null!==g?c=0:c=-1;if(g&&null!==g&&"undefined"!==typeof g.offsetLeft)for(;g;)c+=0<=g.offsetLeft?g.offsetLeft:0,d+=0<=g.offsetTop?
        g.offsetTop:0,g=g.offsetParent;var e=g=0;b||(b=k.event);if(b.pageX||b.pageY)g=b.pageX,e=b.pageY;else if(b.clientX||b.clientY)if(g=b.clientX,e=b.clientY,a.isIE)if(0<document.body.scrollLeft||0<document.body.scrollTop)g+=document.body.scrollLeft,e+=document.body.scrollTop;else if(0<document.documentElement.scrollLeft||0<document.documentElement.scrollTop)g+=document.documentElement.scrollLeft,e+=document.documentElement.scrollTop;b=0;b=a.isIE?document.body.clientWidth:self.innerWidth-16;var m=!0;if(g>=
        b||!a.sentFullPixel)m=!1;(0<=d||0<=c)&&(g>c&&e>d)&&(g="-"+(g-c),e="-"+(e-d));m&&"1"===a.heatmap&&(a.executePlugin(a.getPluginConfig("heatmap","before")),a.quicksend(a.wtEscape(a.contentId.split(";")[0])+","+g+","+e,"","hm"+(a.fileSuffix?".pl":"")),a.executePlugin(a.getPluginConfig("heatmap","after")))},c=function(){"undefined"!==typeof k.wt_heatmap?k.setTimeout(function(){k.wt_heatmap()},1E3):("undefined"===typeof k.wt_heatmap_retry&&(k.wt_heatmap_retry=0),k.wt_heatmap_retry++,60>k.wt_heatmap_retry&&
    k.setTimeout(function(){c()},1E3))};a.heatmapTrackInit=function(){for(var b=!1,c=0;c<k.webtrekkHeatmapObjects.length;c++)a===k.webtrekkHeatmapObjects[c]&&(b=!0);!b&&(a.heatmap&&"1"===a.heatmap)&&(k.webtrekkHeatmapObjects.push(a),a.registerEvent(document,"mousedown",d),a.registerEvent(document,"touchstart",d))};a.heatmapTrackInit();a.heatmapOn&&!a.disableOverlayView&&a.startHeatmapOrOverlay("heatmap",c)},ja=function(a,d,c){a.setProperty("reporturl","report2.webtrekk.de/cgi-bin/wt");a.setProperty("disableOverlayView",
        !1);var b=function(b){var c=a.reporturl;-1!==b.search(/^((http[s]?:\/\/)?(report\d+|analytics)\.webtrekk\.(com|de)\/)/)&&(c=b.split("/"),c.pop(),c=c.join("/"));return c};a.searchContentIds=function(){var b=0,c=0;a.contentIds=a.wtEscape(a.contentId.split(";")[0]);do{b++;var d=a.urlParam(document.location.href,"wt_contentId"+b,!1);d&&(a.contentIds+="&wt_contentId"+b+"="+a.wtEscape(d),c++)}while(c>=b)};a.startHeatmapOrOverlay=function(c,d){a.searchContentIds();a.urlParam(a.wtHref(),"wt_reporter",!1)?
        a.reporturl=b(a.urlParam(a.wtHref(),"wt_reporter",!1)):a.getCookie("wt_overlayFrame")&&(a.reporturl=b(a.getCookie("wt_overlayFrame")));-1===a.reporturl.search(/http|https/)&&(a.reporturl=document.location.protocol+"//"+a.reporturl);if(a.contentIds){var g=a.reporturl+"/"+c+".pl?wt_contentId="+a.contentIds+"&x="+(new Date).getTime();if(a.include(g))if("heatmap"===c&&(-1!==navigator.userAgent.indexOf("MSIE 6")&&-1!==navigator.userAgent.indexOf("Windows NT 5.0"))&&alert("Click OK to start heatmap."),
    "complete"!==document.readyState)a.registerEvent(k,"load",d);else return d()}return 0};(function(){for(var b=!1,h=0;h<k.webtrekkUnloadObjects.length;h++)a===k.webtrekkUnloadObjects[h]&&(b=!0);b||k.webtrekkUnloadObjects.push(a);ha(a);ia(a,d,c)})()},ka=function(){var a=this,d="customClickParameter customSessionParameter customCampaignParameter customEcommerceParameter customParameter crmCategory urmCategory contentGroup productCategory".split(" "),c={numberSearchResults:[d[4],771],errorMessages:[d[4],
            772],loginStatus:[d[1],800],pixelVersion:[d[1],801],trackingPlatform:[d[1],802],npsScore:[d[6],850],npsScoreFeedback:[d[6],851],productLabel:[d[8],870],productMainCategory:[d[8],871],productSubCategory:[d[8],872],productManufacturer:[d[8],873],productShortDescription:[d[8],874],productLongDescription:[d[8],875],paymentMethod:[d[3],761],shippingService:[d[3],762],shippingSpeed:[d[3],763],shippingCosts:[d[3],764],grossMargin:[d[3],765],orderStatus:[d[3],766],productVariant:[d[3],767],couponValue:[d[3],
            563],productSoldOut:[d[3],760],paywall:[d[4],773],articleTitle:[d[4],774],paywallUser:[d[6],852],pageMainCategory:[d[7],880],pageSubCategory:[d[7],881],pageAuthor:[d[7],882],contentTags:[d[4],775],pageTitle:[d[4],776],pageType:[d[4],777],pageLength:[d[4],778],daysSincePublication:[d[4],779],testVariant:[d[4],781],testExperiment:[d[4],782],email:[d[6],700],emailRID:[d[6],701],emailOptin:[d[6],702],firstName:[d[6],703],lastName:[d[6],704],telefon:[d[6],705],gender:[d[6],706],birthday:[d[6],707],country:[d[6],
            708],city:[d[6],709],postalCode:[d[6],710],street:[d[6],711],streetNumber:[d[6],712],validation:[d[6],713]},b={},f=function(){for(var a=0;a<d.length;a++)b[d[a]]={}};f();this.list={};this.clear=function(){b={};a.list={};f()};this.get=function(c){c="all"===c?b:"undefined"!==typeof a.list[c]?a.list[c]:null;return c};this.put=function(d,f){if(f&&"undefined"!==typeof c[d]){var e=c[d];"undefined"===typeof b[e[0]]&&(b[e[0]]={});b[e[0]][e[1]]=f;a.list[d]=f}return a};this.remove=function(d){var f=null;if("undefined"!==
        typeof c[d]){var e=c[d];"undefined"!==typeof b[e[0]]&&"undefined"!==typeof b[e[0]][e[1]]&&(f=b[e[0]][e[1]],delete b[e[0]][e[1]]);delete a.list[d]}return f}},la=function(a){a.PredefinedParameter=ka;a.checkCustomParameter=function(d,c){var b="";if("object"===typeof d)for(var f in d)isNaN(parseInt(f))||("undefined"===typeof d[f]||"string"!==typeof d[f]||""===d[f])||(a.checkSC("custom")&&(d[f]=a.decrypt(d[f])),-1===a.paramFirst.indexOf(c+f+";")&&(b+="&"+c+f+"="+a.wtEscape(d[f])));return b};a.mergeCustomParameter=
        function(a,c){var b=a;b||(b={});for(var f in c)b[f]=c[f];return b}},ma=function(a,d,c){var b=this;b.item=c;b.href="undefined"!==typeof c.href?c.href:"";b.href||(b.href=a.getAttribute(c,"href")?a.getAttribute(c,"href"):"");b.linkIdByNameOrId=a.getAttribute(c,"name")?a.getAttribute(c,"name"):"";b.linkIdByNameOrId||(b.linkIdByNameOrId=a.getAttribute(c,"id")?a.getAttribute(c,"id"):"");b.linkId="";b.action="link";b.isDownloadFile=!1;b.linktrackOut=!1;b.isInternalLink=function(){var d;if(a.linkTrackDownloads){d=
        a.linkTrackDownloads.split(";");for(var h=b.href.split("."),h=h.pop(),g=0;g<d.length;g++)if(d[g]===h){b.isDownloadFile=!0;break}}b.linktrackOut=a.domain&&!a.isOwnDomain(b.href);if(b.isDownloadFile||"_blank"===c.target)b.action="click";d=b.href;var h=d.toLowerCase(),g=d.split("#")[0],e=document.location,k=b.item,p=a.getAttribute,l=p(k,"onclick"),n=p(k,"onmousedown"),k=p(k,"ontouchstart");d=a.noDelayLinkTrackAttribute?!!a.getAttribute(c,a.noDelayLinkTrackAttribute):!(d&&!(0===h.indexOf("javascript:")||
        0===h.indexOf("#")||"click"===b.action||g===e.href.split("#")[0]&&-1!==d.indexOf("#")||g===e.pathname.split("#")[0]&&-1!==d.indexOf("#")||l&&-1!==l.search(/return false[;]?$/)||n&&-1!==n.search(/return false[;]?$/)||k&&-1!==k.search(/return false[;]?$/)));return d};b.getCCParams=function(){var c="";if(a.config.customClickParameter){var d="undefined"!==typeof a.config.customClickParameter[b.linkIdByNameOrId]?a.config.customClickParameter[b.linkIdByNameOrId]:!1;d||(d=a.config.customClickParameter);
        for(var g in d)!isNaN(parseInt(g))&&("string"===typeof d[g]&&d[g])&&(a.checkSC("custom")&&(d[g]=a.decrypt(d[g])),c+="&ck"+g+"="+a.wtEscape(d[g]))}return c};b.setJSONParams=function(){b.linkId||(b.linkId=a.getAttribute(c,a.linkTrackAttribute));null!==a.getJSON(b.linkId)&&(a.parseJSON(a.getJSON(b.linkId)),b.linkId=a.config.linkId)};b.getLinkId=function(){b.linkId=a.getAttribute(c,a.linkTrackAttribute);b.setJSONParams();if("link"===a.linkTrack){var d=b.href.indexOf("//");b.href=0<=d?b.href.substr(d+
        2):b.href;a.linkTrackPattern&&(a.linkTrackReplace||(a.linkTrackReplace=""),b.href=b.href.replace(a.linkTrackPattern,a.linkTrackReplace));b.linkId=(b.linkId?b.linkId+".":"")+b.href.split("?")[0].split("#")[0].replace(/\//g,".");d=[];a.linkTrackParams&&(d=a.linkTrackParams.replace(/;/g,",").split(","));for(var h=0;h<d.length;h++){var g=a.urlParam(b.href,d[h],"");g&&(b.linkId+="."+d[h]+"."+g)}}return b.linkId}},na=function(a){var d=this;d.triggerObjectName="__"+(new Date).getTime()+"_"+parseInt(1E3*
        Math.random());var c=function(b,c){var g=c[d.triggerObjectName];a.config=a.getConfig(!0);a.config.customClickParameter=a.customClickParameter;a.ccParams=g.getCCParams();var e=a.config.linkId=g.getLinkId();a.linktrackOut=g.linktrackOut;a.sendinfo(a.config,e,g.action)},b=function(b){a.registerEvent(b,"click",function(h){if(h.which&&1===h.which||h.button&&1===h.button)a.delayLinkTrack&&("function"===typeof h.preventDefault&&!b[d.triggerObjectName].isInternalLink())&&(h.preventDefault(),k.setTimeout(function(){document.location.href=
        b.href},a.delayLinkTrackTime)),c(h,b)})};d.linkTrackInit=function(){if(a.linkTrack&&("link"===a.linkTrack||"standard"===a.linkTrack)){for(var c=!1,h=0;h<k.webtrekkLinktrackObjects.length;h++)a===k.webtrekkLinktrackObjects[h]&&(c=!0);c||k.webtrekkLinktrackObjects.push(a);c=0;for(h=document.links.length;c<h;c++){var g=document.links[c],e=a.getAttribute(g,a.linkTrackAttribute),m=a.getAttribute(g,"href");(a.linkTrackIgnorePattern&&m&&-1===m.search(a.linkTrackIgnorePattern)||!a.linkTrackIgnorePattern)&&
    ("undefined"===typeof g[d.triggerObjectName]&&(e||"link"===a.linkTrack))&&(g[d.triggerObjectName]=new ma(a,d,g),b(g))}}}},oa=function(a){a.linkTrackObject=new na(a);a.linkTrackInstall=a.linkTrackObject.linkTrackInit;a.linkTrackInit=a.linkTrackObject.linkTrackInit;"complete"===document.readyState?a.linkTrackInit():a.registerEvent(k,"load",function(){a.linkTrackInit()})},pa=function(a,d,c){var b=null,f=d.type,h=a.getFormFieldName(d),g=a.getFormFieldValue(d);this.close=function(){null!==b&&(g=a.getFormFieldValue(d),
    "radio"!==f&&(k.clearInterval(b),b=null,a.formFieldData[h][c]=[f,g]),a.formFieldDataPathAnalysis.push([h,f,g]))};this.start=function(e){null===b&&(b=k.setInterval(function(){"undefined"!==typeof d&&(d&&null!==d&&"undefined"!==typeof a.formFieldData[h])&&("string"!==typeof a.formFieldData[h][0]&&"string"!==typeof a.formFieldData[h][a.formFieldData.length-1])&&(g=a.getFormFieldValue(d),a.formFieldData[h][c]=[f,g])},50),e||delete a.formFieldDataUnused[h])}},C=function(a,d){var c=this;c.formObject=!1;
        c.formFocus=!1;c.formName=!1;c.form=a.form;c.formSubmit=!1;c.formFieldData={};c.formFieldDataUnused={};c.formFieldDataPathAnalysis=[];c.triggerObjectName="__"+(new Date).getTime()+"_"+parseInt(1E3*Math.random());var b=function(a){return"hidden"!==a&&"button"!==a&&"image"!==a&&"reset"!==a&&"submit"!==a&&"fieldset"!==a},f=function(a){return"select-multiple"!==a&&"select-one"!==a&&"checkbox"!==a&&"radio"!==a},h=function(a,d,e){b(a.type)&&c.formObject&&(d||(c.formFocus=a),"undefined"===typeof a[c.triggerObjectName]&&
            (a[c.triggerObjectName]=new pa(c,a,e),a[c.triggerObjectName].start(d)))},g=function(d,e){a.registerEvent(d,"focus",function(){h(d,!1,e)});a.registerEvent(d,"blur",function(){b(d.type)&&(c.formObject&&d&&d&&"undefined"!==typeof d[c.triggerObjectName])&&(d[c.triggerObjectName].close(),"radio"!==d.type&&delete d[c.triggerObjectName])})},e=function(){if(c.form&&!c.formObject)for(var a=document.forms,b=0,d=a.length;b<d;b++){var e=a[b];if("undefined"!==typeof e.elements.wt_form){c.formObject=e;break}}},
            m=function(a){!c.form||a.target!==c.formObject&&a.srcElement!==c.formObject||(c.formSubmit=!0)},p=function(){e();if(c.formObject){var f=a.getAttribute(c.formObject,a.formAttribute);c.formName=f?f:a.contentId.split(";")[0];for(var f=0,v=c.formObject.elements,da=v.length;f<da;f++){var w=v[f],l=c.getFormFieldName(w);if(b(w.type)&&l&&null!==l){"undefined"===typeof c.formFieldData[l]&&(c.formFieldData[l]=[]);"undefined"===typeof c.formFieldDataUnused[l]&&(c.formFieldDataUnused[l]=[]);var n=c.getFormFieldValue(w);
                c.formFieldData[l].push([w.type,n]);c.formFieldDataUnused[l].push([w.type,n]);l=c.formFieldData[l].length-1;"radio"===w.type&&w.checked&&h(w,!0,l);g(w,l)}}a.registerEvent(c.formObject,"submit",m);a.registerEvent(k,"beforeunload",function(){d(c)});a.registerEvent(k,"unload",function(){d(c)})}},l=function(b){var d=[];a.formFullContent&&(d=a.formFullContent.split(";"));if(a.formAnonymous||f(b.type)){for(var e=0;e<d.length;e++)if(d[e]===c.getFormFieldName(b))return!1;return!0}return!1},n=function(b,c){var d=
                c;d||(d=b);var e=a.getAttribute(d,a.formValueAttribute).replace(/[\.;\|]/g,"_");return f(b.type)?a.maxlen(a.wtUnescape(d.value),110):l(b)?"anon":a.maxlen(a.wtUnescape(e),110)},r=function(a,b,d,e){var f=a.replace(/[\.;\|]/g,"_")+".",f=f+(b+"|")+(d+"|");return f=e?f+"0":f+(c.formFocus&&c.getFormFieldName(c.formFocus)===a?"1":"0")},q=function(a,b){for(var c=[],d=0,e=b.length;d<e;d++)if("undefined"!==typeof a[b[d]])if("select-multiple"===a[b[d]][0])for(var f=a[b[d]][1].split("|"),h=0,g=f.length;h<g;h++)c.push(r(b[d],
                a[b[d]][0],f[h]));else c.push(r(b[d],a[b[d]][0],a[b[d]][1]));return c.join(";")},s=function(a){for(var b in a){var c=b+"";if(1<a[c].length){for(var d=!1,e=0;e<a[c].length;e++)if("empty"!==a[c][e][1]){a[c]=a[c][e];d=!0;break}if(d)continue}a[c]=a[c][0]}},u=function(){if(!c.formObject)return"";s(c.formFieldData);s(c.formFieldDataUnused);var b=[],d;d=[];if("undefined"!==typeof c.formObject.elements.wt_fields){var e=c.formObject.elements.wt_fields.value;e&&(d=e.split(";"))}if(0>=d.length)for(var f in c.formFieldData)"string"===
            typeof f&&f&&d.push(f);e=!1;if(a.formPathAnalysis){(f=q(c.formFieldDataUnused,d))&&b.push(f);f=0;for(var h=c.formFieldDataPathAnalysis.length;f<h;f++){var g=c.formFieldDataPathAnalysis,k;a:{k=0;for(var l=d.length;k<l;k++)if(g[f][0]===d[k]){k=!0;break a}k=!1}k&&(e=!0,b.push(r(g[f][0],g[f][1],g[f][2],!0)))}e&&(d=b[b.length-1],d=d.substr(0,d.length-1),b[b.length-1]=d+"1")}else return q(c.formFieldData,d);return b.join(";")};c.getFormFieldName=function(b){var c=b.name;a.formFieldAttribute&&(c="",(b=a.getAttribute(b,
            a.formFieldAttribute))||null!==b)&&(c=b);return c};c.getFormFieldValue=function(b){var d=b.type,e="";if("select-multiple"===d){for(var e=[],f=0,h=b.options,g=h.length;f<g;f++)h[f].selected&&e.push(n(b,h[f]));0>=e.length&&e.push("empty");e=e.join("|")}else"select-one"===d?(e="",-1!==b.selectedIndex&&((e=n(b,b.options[b.selectedIndex]))&&null!==e||(e="empty"))):"checkbox"===d||"radio"===d?(e="",b.checked?(e=n(b))||(e="checked"):e="empty"):"hidden"!==d&&("button"!==d&&"image"!==d&&"reset"!==d&&"submit"!==
            d)&&(f=(e=n(b))?"filled_out":"empty",l(b)||(f=e),h=c.getFormFieldName(b),"undefined"!==typeof a.formFieldDefaultValue[h]&&a.formFieldDefaultValue[h]===e&&"empty"!==f&&(f="empty"),f&&null!==f||(f="empty"),e=f);return l(b)&&"select-multiple"!==d&&"empty"!==e&&"filled_out"!==e?"anon":e};c.formTrackInstall=function(a){c.formObject=a?a:document.forms[0]?document.forms[0]:!1;c.formObject&&(c.form="1",p())};c.getFormTrackingData=function(){var b="";if(c.formObject){var d=u();if(d){var e=c.formSubmit;a.formSubmit&&
        (e=a.formSubmit);b+="&fn="+a.wtEscape(c.formName)+"%7C"+(e?"1":"0");b+="&ft="+a.wtEscape(d)}c.formSubmit=!1;a.formSubmit=!1;c.formName=!1;c.formObject=!1;c.formFocus=!1;c.formFieldData={};c.formFieldDataUnused={};c.formFieldDataPathAnalysis=[]}return b};c.formTrackSubmit=function(){c.formSubmit=!0};c.sendFormRequest=function(){"1"!==a.cookie||(a.optOut||a.deactivatePixel)||a.firstParty();"function"===typeof a.beforeUnloadPixel?a.beforeUnloadPixel():a.executePlugin(a.getPluginConfig("form","before"));
            var b=c.getFormTrackingData();b&&a.quicksend(a.wtEscape(a.contentId.split(";")[0])+",1,"+a.baseparams(),b);"function"===typeof a.afterUnloadPixel?a.afterUnloadPixel():a.executePlugin(a.getPluginConfig("form","after"))};c.updateFormFieldStatus=function(a){if(a&&null!==a&&"undefined"!==typeof a.type){var b=a.type,d=c.getFormFieldName(a),e=c.getFormFieldValue(a);d&&(e&&"undefined"!==typeof c.formFieldData[d])&&(c.formFieldData[d].splice(0,0,[b,e]),c.formFieldDataPathAnalysis.push([d,b,e]),c.formFocus=
            a,delete c.formFieldDataUnused[d])}};c.init=function(){c.form&&("1"===c.form&&!c.formObject)&&p();return c}},qa=function(a){a.multipleFormArray=[];var d=function(b){for(var c=0;c<a.multipleFormArray.length;c++)if(a.multipleFormArray[c].formObject===b)return a.multipleFormArray[c];return!1},c=function(b){if(b&&"undefined"!==typeof b.elements&&!d(b)){var c=new C(a,function(b){z(a,"form","form",b)});a.multipleFormArray.push(c);c.formTrackInstall(b)}};a.multipleFormTrackInstall=c;a.multipleFormTrackInit=
        c;a.multipleFormTrackSubmit=function(a){a&&(a=d(a))&&a.formTrackSubmit()};a.sendMultipleFormRequest=function(b){if(b)(b=d(b))&&b.sendFormRequest();else for(b=0;b<a.multipleFormArray.length;b++)a.multipleFormArray[b].sendFormRequest()};a.updateMultipleFormFieldStatus=function(a,c){if(a){var h=d(a);h&&h.updateFormFieldStatus(c)}}},ra=function(a,d){var c=this;c.name=a?a:"";c.elements=d?d:[];c.add=function(a){a&&null!==a&&c.elements.push(a);return c};c.getAttribute=function(){return a};c.addEventListener=
        c.removeEventListener=function(){}},z=function(a,d,c,b){"1"!==a.cookie||(a.optOut||a.deactivatePixel)||a.firstParty();(c=c?c:"")||(c=a.formObject&&"noForm"!==d?"form":"link");"function"===typeof a.beforeUnloadPixel?a.beforeUnloadPixel():"form"===c&&a.executePlugin(a.getPluginConfig("form","before"));var f="";if(a.config.linkId&&(f+="&ct="+a.wtEscape(a.maxlen(a.wtUnescape(a.config.linkId),255)))){a.linktrackOut&&(f+="&ctx=1");var h=a.ccParams;"string"===typeof h&&""!==h&&(f+=h)}if(a.wtEp)if(a.wtEpEncoded)f+=
        a.wtEp;else if(h=a.wtEp,"string"===typeof h&&""!==h)for(var h=h.split(/;/),g=0;g<h.length;g++)if("undefined"!==typeof h[g]){var e=h[g].split(/\=/);a.checkSC("custom")&&(e[1]=a.decrypt(e[1]));e[1]=a.wtEscape(e[1]);f+="&"+e[0]+"="+e[1]}"noForm"!==d&&(f+=b.getFormTrackingData());""!==f&&(a.quicksend(a.wtEscape(a.contentId.split(";")[0])+",1,"+a.baseparams(),f),a.config.linkId="",a.ccParams="",a.wtEp="");"function"===typeof a.afterUnloadPixel?a.afterUnloadPixel():"form"===c&&a.executePlugin(a.getPluginConfig("form",
        "after"))},sa=function(a){a.formTrackObject=new C(a,function(d){z(a,"form","form",d)});a.formTrackInstall=a.formTrackObject.formTrackInstall;a.formTrackInit=a.formTrackObject.formTrackInstall;a.formTrackSubmit=a.formTrackObject.formTrackSubmit;a.sendFormRequest=a.formTrackObject.sendFormRequest;a.updateFormFieldStatus=a.formTrackObject.updateFormFieldStatus;"complete"===document.readyState?a.formTrackObject.init():a.registerEvent(k,"load",function(){a.formTrackObject.init()});a.CustomForm=ra;qa(a)},
    ta=function(){var a="",d="",c=!1,b=!0,f=0,h=null,g=!1,e=function(){},m=function(){},p=function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)},l=function(){var a=1E3;h=k.setInterval(function(){0>=a&&(k.clearInterval(h),g=!1,c||(b=!0,f++,e(f)));a-=5},5)};this.isPageHidden=function(){return c};this.isPageVisible=function(){return b};this.setVisibleCall=function(a){e=a};this.setHiddenCall=function(a){m=a};"undefined"!==typeof document.hidden?(a="hidden",d=
        "visibilitychange"):"undefined"!==typeof document.mozHidden?(a="mozHidden",d="mozvisibilitychange"):"undefined"!==typeof document.msHidden?(a="msHidden",d="msvisibilitychange"):"undefined"!==typeof document.oHidden?(a="oHidden",d="ovisibilitychange"):"undefined"!==typeof document.webkitHidden&&(a="webkitHidden",d="webkitvisibilitychange");a&&(c=document[a],(b=!c)&&f++,function(){p(document,d,function(){(c=document[a])?(k.clearInterval(h),b=g=!1,m()):g||(g=!0,l())})}())},ua=function(a){a.setProperty("tabBrowsing",
        !1);var d=[],c=[],b=null,f=function(){b=new ta;b.setVisibleCall(function(b){if(1<b&&0<c.length){var f=c[0].split("&");b-=1;f[1]="tb="+b+"&cp770="+b+"&"+f[1];a.sendPixel(f.join("&"),c[1])}for(var e=0,k=d.length;e<k;e++)f=d[e][0],b=d[e][1],a.sendPixel(f,b),"wt"===b&&-1===f.search(/&(ct|fn|ft)=.+&/)&&(c=[f,b]);d=[]})};a.tabBrowsing&&f();a.sendTabBrowsingPixel=function(f,g){b.isPageVisible()?(a.sendPixel(f,g),"wt"===g&&-1===f.search(/&(ct|fn|ft)=.+&/)&&(c=[f,g])):d.push([f,g])};a.startTabBrowsing=function(){null===
    b&&(a.tabBrowsing=!0,f())}};k.webtrekkV3=k.WebtrekkV3=function(a){var d=k.webtrekkConfig;a||(a=k.webtrekkConfig);this.version="441";for(var c=[L,W,X,$,ba,ca,ga,ja,la,oa,sa,ua],b=0;b<c.length;b++)c[b](this,a,d)}})(window);
if("object"===typeof webtrekkConfig&&"object"===typeof webtrekkConfig.safetag&&-1===document.cookie.indexOf("wt_r=1")){var wts=wts||[],wt_safetagConfig={async:"undefined"!==typeof webtrekkConfig.safetag.async?webtrekkConfig.safetag.async:!0,timeout:"undefined"!==typeof webtrekkConfig.safetag.timeout?webtrekkConfig.safetag.timeout:2E3,safetagDomain:"undefined"!==typeof webtrekkConfig.safetag.safetagDomain?webtrekkConfig.safetag.safetagDomain:!1,safetagId:"undefined"!==typeof webtrekkConfig.safetag.safetagId?
        webtrekkConfig.safetag.safetagId:!1,customDomain:"undefined"!==typeof webtrekkConfig.safetag.customDomain?webtrekkConfig.safetag.customDomain:!1,customPath:"undefined"!==typeof webtrekkConfig.safetag.customPath?webtrekkConfig.safetag.customPath:!1,option:"undefined"!==typeof webtrekkConfig.safetag.option?webtrekkConfig.safetag.option:{}};(function(b,g){var d=function(a){try{return encodeURIComponent(a)}catch(b){return escape(a)}},e=document.location.protocol;if("http:"==e||"https:"==e){var a="";b.customDomain&&
b.customPath?a=e+"//"+b.customDomain+"/"+b.customPath:b.safetagDomain&&(b.safetagId&&-1!==b.safetagId.search(/^\d+$/))&&(a=e+"//"+b.safetagDomain+"/resp/api/get/"+b.safetagId+"?url="+d(document.location.href));if(a){for(var f in b.option)a+="&"+f+"="+d(b.option[f]);webtrekkV3.prototype.safetag=b;webtrekkV3.prototype.safetagInProgress=!0;webtrekkV3.prototype.safetagParameter={};webtrekkV3.prototype.update=function(){};window.wts=g;window.safetagLoaderHandler=function(a,b){if(a&&b)if("onerror"==b)webtrekkV3.prototype.safetagInProgress=
    !1;else if("onload"==b){if("undefined"!==typeof wt_r&&!isNaN(wt_r)){var d=new Date;document.cookie="wt_r=1;path=/;expires="+d.toUTCString(d.setTime(d.getTime()+1E3*parseInt(wt_r)))}webtrekkV3.prototype.safetagInProgress=!1}else"onreadystatechange"!=b||"loaded"!=a.readyState&&"complete"!=a.readyState||(a.onreadystatechange=null,a.onload(c))};if(b.async||"complete"===document.readyState||"interactive"===document.readyState){var d=document.getElementsByTagName("script")[0],c=document.createElement("script");
    c.async=b.async;c.type="text/javascript";c.onerror=function(){"undefined"!==typeof window.wt_mcp_hide&&"function"===typeof window.wt_mcp_hide.show&&(window.wt_mcp_hide.show(),window.wt_mcp_hide.show=function(){});safetagLoaderHandler(c,"onerror")};c.onload=function(){safetagLoaderHandler(c,"onload")};c.onreadystatechange=function(){safetagLoaderHandler(c,"onreadystatechange")};c.src=a;d.parentNode.insertBefore(c,d)}else a='<script type="text/javascript" src="'+a+'" onerror="safetagLoaderHandler(this,\'onerror\')"',
    a+=" onload=\"safetagLoaderHandler(this,'onload')\"",a+=" onreadystatechange=\"safetagLoaderHandler(this,'onreadystatechange')\"",a+=">\x3c/script>",document.write(a)}}})(wt_safetagConfig,wts)};
/** End webtrekk_v4.js */
